### ISSUE TITLE
en_coref-4.0.0, difference between website model and shared model

### ISSUE THREAD

**Issue by boehm-e** [huggingface/neuralcoref#100]
Hi,
I am trying to have the same results as the website:
When i use the en_coref_lg 3.0.0 model and even if i replace the `neuralcoref` folder by the new 4.0.0 release (https://github.com/huggingface/neuralcoref-models/releases/), it has no effects:

in the following sentence,  `it` is replaced by `One day after a heavy meal`:

`Once upon a time a lion lived in a forest. One day after a heavy meal it was sleeping.  After a while, a mouse came and it started to play.`

so in my version of `en_coref_lg`, i get : 
_One_ day after a heavy meal **One day after a heavy meal** was sleeping__

but it seems to be working fine on the web demo [https://huggingface.co/coref/?text=my_text.](https://huggingface.co/coref/?text=Once%20upon%20a%20time%20a%20lion%20lived%20in%20a%20forest.%20One%20day%20after%20a%20heavy%20meal%20it%20was%20sleeping.%20%20After%20a%20while%2C%20a%20mouse%20came%20and%20it%20started%20to%20play.)

![image](https://user-images.githubusercontent.com/11290215/46793803-ce755180-cd46-11e8-8f97-b39fe7473751.png)

So my question is:
Are they any way to get the same results as the web demo?
As you are providing the **4.0.0** model, i was expecting to have better results (as on the web), but i have not (for my case), so are you using an other model ? And are you planning to share it?

Thank you very much for this amazing library, and for open-sourcing it :)
Any help would be appreciated

**Comment by szittrower** [comment]
I believe the website demo still uses Neural Coref 2.0 model and code. As far as I'm aware you are not able to get the output scores from NeuralCoref after 3.0. I'd be interested if that were not the case.

**Comment by thomwolf** [comment]
Yes our demo is still based on NeuralCoref 2.0
The new release (NeuralCoref 4.0) now outputs the coreference scores as well (see the README for details).
