### ISSUE TITLE
doc._.coref_resolved returns empty string if no coreference

### ISSUE THREAD

**Issue by JohnGiorgi** [huggingface/neuralcoref#101]
I noticed that `doc._.coref_resolved` will return the empty string if there is no coreference mentions in a document. For example:

```python
>>> import en_coref_md
>>> nlp = en_coref_md.load()
>>> text = 'There is no coreference mentions here!'
>>> doc = nlp(text)
>>> resolved_text = doc._.coref_resolved
>>> resolved_text
>>> ''
```

Is this expected behaviour? I would have expected `doc._.coref_resolved` to just return the same text that came in if no coreference mentions were found. Apologies if this behaviour is documented somewhere, I couldn't find it if so!

**Comment by shellshock1911** [comment]
This is definitely a significant issue for someone not aware of it if they're about to process tons of documents for another task. The most logical behavior to me at least would be to return the original text, but that isn't what happens as mentioned. Internally, there should be a check to `doc._.has_coref`, and if that returns `False`, then no further processing is need.

**Comment by JohnGiorgi** [comment]
I agree! I’ll see if I can get around to opening a pull request. Should be really straightforward.

**Comment by thomwolf** [comment]
Fixed now.
