### ISSUE TITLE
spacy.strings.StringStore has the wrong size, try recompiling

### ISSUE THREAD

**Issue by fersarr** [huggingface/neuralcoref#103]
Spacy works perfectly fine for me with the usual spacy-provided models, but trying to load `en_coref_md` or  `en_coref_lg` fails with the following message:

```
$ pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_md-3.0.0/en_coref_md-3.0.0.tar.gz
$ python
Python 3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import spacy
>>> spacy.load('en_coref_md')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/yyy/miniconda2/envs/xxx/lib/python3.7/site-packages/spacy/__init__.py", line 17, in load
    return util.load_model(name, **overrides)
  File "/yyy/miniconda2/envs/xxx/lib/python3.7/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/yyy/miniconda2/envs/xxx/lib/python3.7/site-packages/spacy/util.py", line 134, in load_model_from_package
    cls = importlib.import_module(name)
  File "/yyy/miniconda2/envs/xxx/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/yyy/miniconda2/envs/xxx/lib/python3.7/site-packages/en_coref_md/__init__.py", line 6, in <module>
    from en_coref_md.neuralcoref import NeuralCoref
  File "/yyy/miniconda2/envs/xxx/lib/python3.7/site-packages/en_coref_md/neuralcoref/__init__.py", line 1, in <module>
    from .neuralcoref import NeuralCoref
  File "strings.pxd", line 23, in init en_coref_md.neuralcoref.neuralcoref
ValueError: spacy.strings.StringStore has the wrong size, try recompiling. Expected 88, got 112

>>> spacy.__version__
'2.0.11'
```

My environment:
```
python 3.7
spacy 2.0.11
mac
```

Not sure if this makes any difference, but spacy was installed via conda while coref was installed via pip. This is part of the output of ```conda list```
```
spacy                     2.0.11           py37h6440ff4_2
en-coref-md               3.0.0                     <pip>
```

**Comment by fersarr** [comment]
upgrading to spacy 2.0.16 gave me error in issue https://github.com/huggingface/neuralcoref/issues/102

**Comment by fersarr** [comment]
I get the same error with `spacy 2.0.13` (from conda-forge) and python `3.6.6`:
```
ValueError: spacy.strings.StringStore has the wrong size, try recompiling. Expected 88, got 112
```

**Comment by soumyagk** [comment]
It worked for me with `spacy==2.0.12` and `thinc==6.10.3`. And that combination alone. spacy's `2.0.11` and `2.0.13` did not work for me.

**Comment by respectPotentialEnergy** [comment]
FWIW I have `spacy==2.0.12` and `thinc==6.10.3` installed via conda (python 3.6.7) and couldn't get it to work. If I `import spacy; nlp=spacy.load('en_coref_md')`, I get a `SystemError: Missing type object`, but if I `import en_coref_md; nlp = en_coref_md.load()`, I get the same error as above, `ValueError: spacy.strings.StringStore has the wrong size, try recompiling. Expected 88, got 112`

**Comment by soumyagk** [comment]
Can you try with system installed python instead of conda-installed? Make sure to create a python virtual environment first though before installing any packages and testing the neural-coref model. 
```
# system installed python3.6
python3.6 -m venv my-env
source my-env/bin/activate
pip install spacy==2.0.12
...
```
I used to face a lot of inconsistency in dependencies using conda (the very things it was supposed to solve 😏 ). I find it much easier to work with a clean python virtual environment created from the system installed python.

**Comment by kaiserama** [comment]
Not sure if this is other people's problem but for me it was because of the version of Neuralcoref.  My system had installed 3.1 but 2.0 is the only compatible version with the Spacy 2.0.12 version I was using.

Additionally no version of 2.0 is available on PyPi so you'll have to download the tar.gz and pip install from that version.

Download version 2.0 [here](https://github.com/huggingface/neuralcoref/releases/tag/2.0)

Then just run `pip install neuralcoref-2.0.tar.gz` (assuming you download the tar.gz to the directory you're in) or target the URL from above.

Everything worked for me after that.  Hope it helps!

**Comment by suriak** [comment]
Faced the same issue and got resolved by using `spacy==2.0.12 `

`import spacy
spacy.__version__
'2.0.12'
import en_coref_md
nlp = en_coref_md.load()
doc = nlp(u'John owns a car. He is rich')
doc._.coref_clusters
[John: [John, He]]`

**Comment by thomwolf** [comment]
Should be fixed with the new release (NeuralCoref 4.0) and SpaCy 2.1+.
Feel free to open new issues if some installation problem are still there.
Please check the README for the new installation instructions (simpler now).

**Comment by saippuakauppias** [comment]
@thomwolf not fixed for:
```
➜ pip install -r reqs.txt
Collecting neuralcoref (from -r reqs.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/88/ed/1828b1015b62e938b267d5da781bd9a8f4370b518b0e6e5520935c84a577/neuralcoref-4.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (513kB)
```
And:
```
>>> spacy.__version__
'2.1.3'
```

**Comment by thomwolf** [comment]
What happens when you follow the [instructions in the readme](https://github.com/huggingface/neuralcoref#spacystringsstringstore-size-changed-error) for this error?

**Comment by saippuakauppias** [comment]
That helped!
Thank you, I did not read carefully and missed this moment.

**Comment by hiwaveSupport** [comment]
I am getting the same issue.
Followed your readme as-is to uninstall and reinstall using --no-binary, spacy install worked and model download worked.
/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)
Segmentation fault (core dumped)

Below is env install:
pip list
Package                            Version 
---------------------------------- --------
 neuralcoref                        4.0     
spacy                              2.1.4   
Python 3.7.3

**Comment by omstuhler** [comment]
I have no issues installing via `pip install neuralcoref`. However I get the same warning as above when trying to `import neuralcoref`:

```
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)
```

I can even add the neuralcoref to a pipeline without getting an error:

```
coref = neuralcoref.NeuralCoref(nlp.vocab)
nlp.add_pipe(coref, name='neuralcoref')
```

However, when trying to run the pipeline, my kernel dies.

spacy 2.1.4
Python 3.6.8
neuralcoref 4.0 
mac



On a further note, when trying to install via `pip install neuralcoref --no-binary neuralcoref`, I get:
```
gcc: error: unrecognized command line option ‘-stdlib=libc++’
    error: command 'gcc' failed with exit status 1
```

**Comment by ChengYJon** [comment]
similar to omstuhler, I followed the readme. The download and install works fine.

Importing results in: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)

**Comment by BvdM0** [comment]
Same problem as ChengYJon and omstuhler. I followed the readme, and tried pip install neuralcoref --no-binary neuralcoref. When I then run import neuralcoref I still get the error
`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)`

**Comment by codewpf** [comment]
Same problem as BvdM0 and CHengYJon.

spacy 2.1.8
Python 3.7
neuralcoref 4.0

**Comment by StrangeTcy** [comment]
Same problem as well:

spacy 2.1.8
python 3.6.8
neuralcoref 4.0

**Comment by svlandeg** [comment]
This is an old thread, and already closed, but for anyone coming here from a search engine: 

As a workaround for the incompatibility issue, you can either downgrade spaCy to 2.1.0, or [build neuralcoref from source](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source) if you want to use a more recent version of spaCy.

We plan on keeping the releases of neuralcoref and spaCy more in-sync in the future. Merging this with Issue #197.
