### ISSUE TITLE
 Loading NeuralCoref as a spaCy pipeline component with new model

### ISSUE THREAD

**Issue by jdliu18** [huggingface/neuralcoref#104]
Hi,

Thank you for sharing this great library. It is really useful for coreference resolution.

After I successfully trained the model following the training instructions, I have three best model files. However, I am not sure how to use those models.  Could you explain how can I use the best ranking model for coreference resolution? Specifically, how can I transfer the best ranking model into the weights I needed for loading NeuralCoref as a spaCy pipeline component.

Thanks!

**Comment by kaushik88** [comment]
@jdliu18 - did you figure out a way to do this?

**Comment by thomwolf** [comment]
Should be fixed with the new release (NeuralCoref 4.0) and SpaCy 2.1+.
You can now use any SpaCy (English) model.
Please check the README for the new installation instructions.
