### ISSUE TITLE
include "ios" error in macOs Mojave with spaCy 2.0.12

### ISSUE THREAD

**Issue by nityansuman** [huggingface/neuralcoref#105]
~$ pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz
     .
     .
     .
    en_coref_sm/neuralcoref/neuralcoref.cpp:583:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    2 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    Command "/Users/nityansuman/anaconda3/envs/coref_resolution/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-lfu3euas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-record-fqaackro/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-lfu3euas/

> Python version 3.5.6
> Spacy version 2.0.12
> Cython version 0.28.5
> Conda Env

    ~$ gcc -v
    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
    Apple LLVM version 10.0.0 (clang-1000.10.44.4)
    Target: x86_64-apple-darwin18.0.0
    Thread model: posix
    InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by kteli** [comment]
uninstall XCODE
