### ISSUE TITLE
Failed building wheel for en-coref-sm

### ISSUE THREAD

**Issue by nityansuman** [huggingface/neuralcoref#106]
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz
Collecting https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz
  Downloading https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz (77.8MB)
    100% |████████████████████████████████| 77.8MB 487kB/s 
Requirement already satisfied: spacy>=>=2.0.0a18 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from en-coref-sm==3.0.0) (2.0.13)
Requirement already satisfied: numpy>=1.15.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.15.3)
Requirement already satisfied: msgpack-numpy<0.29,<0.4.4.0murmurhash>=0.28 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.4.3.2)
Requirement already satisfied: cymem<1.32,>=1.30 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.31.2)
Requirement already satisfied: preshed<2.0.0,>=1.0.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.0.1)
Requirement already satisfied: thinc<6.11.0,>=6.10.3 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (6.10.3)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.9.6)
Requirement already satisfied: ujson>=1.35 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.35)
Requirement already satisfied: dill<0.3,>=0.2 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.2.8.2)
Collecting regex==2018.01.10 (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (2.20.0)
Requirement already satisfied: msgpack>=0.3.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from msgpack-numpy<0.29,<0.4.4.0murmurhash>=0.28->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.5.6)
Requirement already satisfied: murmurhash<0.29.0,>=0.28.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.3->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.28.0)
Requirement already satisfied: cytoolz<0.10,>=0.9.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.3->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.9.0.1)
Requirement already satisfied: wrapt<1.11.0,>=1.10.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.3->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.10.11)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.3->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (4.28.1)
Requirement already satisfied: six<2.0.0,>=1.10.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from thinc<6.11.0,>=6.10.3->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.11.0)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (2018.10.15)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (3.0.4)
Requirement already satisfied: toolz>=0.8.0 in ./anaconda3/envs/project-implicit/lib/python3.6/site-packages (from cytoolz<0.10,>=0.9.0->thinc<6.11.0,>=6.10.3->spacy>=>=2.0.0a18->en-coref-sm==3.0.0) (0.9.0)
Building wheels for collected packages: en-coref-sm
  Running setup.py bdist_wheel for en-coref-sm ... error
  Complete output from command /Users/nityansuman/anaconda3/envs/project-implicit/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-sudm1p9g/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-wheel-mjqo577o --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
  copying en_coref_sm/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
  copying en_coref_sm/neuralcoref/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
  copying en_coref_sm/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0
  copying en_coref_sm/en_coref_sm-3.0.0/tokenizer -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0
  copying en_coref_sm/en_coref_sm-3.0.0/meta.json -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
  copying en_coref_sm/en_coref_sm-3.0.0/ner/lower_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
  copying en_coref_sm/en_coref_sm-3.0.0/ner/moves -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
  copying en_coref_sm/en_coref_sm-3.0.0/ner/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
  copying en_coref_sm/en_coref_sm-3.0.0/ner/tok2vec_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
  copying en_coref_sm/en_coref_sm-3.0.0/ner/upper_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
  copying en_coref_sm/en_coref_sm-3.0.0/parser/lower_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
  copying en_coref_sm/en_coref_sm-3.0.0/parser/moves -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
  copying en_coref_sm/en_coref_sm-3.0.0/parser/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
  copying en_coref_sm/en_coref_sm-3.0.0/parser/tok2vec_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
  copying en_coref_sm/en_coref_sm-3.0.0/parser/upper_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
  copying en_coref_sm/en_coref_sm-3.0.0/vocab/vectors -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
  copying en_coref_sm/en_coref_sm-3.0.0/vocab/lexemes.bin -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
  copying en_coref_sm/en_coref_sm-3.0.0/vocab/strings.json -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
  copying en_coref_sm/en_coref_sm-3.0.0/vocab/key2row -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/single_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/pairs_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors/vectors -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors/key2row -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors/vectors -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors
  copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors/key2row -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors
  creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
  copying en_coref_sm/en_coref_sm-3.0.0/tagger/tag_map -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
  copying en_coref_sm/en_coref_sm-3.0.0/tagger/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
  copying en_coref_sm/en_coref_sm-3.0.0/tagger/model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
  copying en_coref_sm/meta.json -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
  copying en_coref_sm/neuralcoref/neuralcoref.pyx -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
  copying en_coref_sm/neuralcoref/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
  copying en_coref_sm/neuralcoref/neuralcoref.pxd -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
  running build_ext
  building 'en_coref_sm.neuralcoref.neuralcoref' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/en_coref_sm
  creating build/temp.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/nityansuman/anaconda3/envs/project-implicit/include -mmacosx-version-min=10.9 -m64 -fPIC -I/Users/nityansuman/anaconda3/envs/project-implicit/include -mmacosx-version-min=10.9 -m64 -fPIC -I/Users/nityansuman/anaconda3/envs/project-implicit/include/python3.6m -I/private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-sudm1p9g/include -I/Users/nityansuman/anaconda3/envs/project-implicit/include/python3.6m -c en_coref_sm/neuralcoref/neuralcoref.cpp -o build/temp.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref/neuralcoref.o
  In file included from en_coref_sm/neuralcoref/neuralcoref.cpp:4:
  In file included from /Users/nityansuman/anaconda3/envs/project-implicit/include/python3.6m/Python.h:25:
  /Users/nityansuman/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
  #include_next <stdio.h>
                ^~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for en-coref-sm
  Running setup.py clean for en-coref-sm
Failed to build en-coref-sm
Installing collected packages: en-coref-sm, regex
  Running setup.py install for en-coref-sm ... error
    Complete output from command /Users/nityansuman/anaconda3/envs/project-implicit/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-sudm1p9g/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-record-c2wxcm2q/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
    copying en_coref_sm/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
    copying en_coref_sm/neuralcoref/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
    copying en_coref_sm/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0
    copying en_coref_sm/en_coref_sm-3.0.0/tokenizer -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0
    copying en_coref_sm/en_coref_sm-3.0.0/meta.json -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
    copying en_coref_sm/en_coref_sm-3.0.0/ner/lower_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
    copying en_coref_sm/en_coref_sm-3.0.0/ner/moves -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
    copying en_coref_sm/en_coref_sm-3.0.0/ner/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
    copying en_coref_sm/en_coref_sm-3.0.0/ner/tok2vec_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
    copying en_coref_sm/en_coref_sm-3.0.0/ner/upper_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/ner
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
    copying en_coref_sm/en_coref_sm-3.0.0/parser/lower_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
    copying en_coref_sm/en_coref_sm-3.0.0/parser/moves -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
    copying en_coref_sm/en_coref_sm-3.0.0/parser/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
    copying en_coref_sm/en_coref_sm-3.0.0/parser/tok2vec_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
    copying en_coref_sm/en_coref_sm-3.0.0/parser/upper_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/parser
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
    copying en_coref_sm/en_coref_sm-3.0.0/vocab/vectors -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
    copying en_coref_sm/en_coref_sm-3.0.0/vocab/lexemes.bin -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
    copying en_coref_sm/en_coref_sm-3.0.0/vocab/strings.json -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
    copying en_coref_sm/en_coref_sm-3.0.0/vocab/key2row -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/vocab
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/single_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/pairs_model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors/vectors -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors/key2row -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/static_vectors
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors/vectors -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors
    copying en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors/key2row -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/neuralcoref/tuned_vectors
    creating build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
    copying en_coref_sm/en_coref_sm-3.0.0/tagger/tag_map -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
    copying en_coref_sm/en_coref_sm-3.0.0/tagger/cfg -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
    copying en_coref_sm/en_coref_sm-3.0.0/tagger/model -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/en_coref_sm-3.0.0/tagger
    copying en_coref_sm/meta.json -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm
    copying en_coref_sm/neuralcoref/neuralcoref.pyx -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
    copying en_coref_sm/neuralcoref/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
    copying en_coref_sm/neuralcoref/neuralcoref.pxd -> build/lib.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
    running build_ext
    building 'en_coref_sm.neuralcoref.neuralcoref' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/en_coref_sm
    creating build/temp.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/nityansuman/anaconda3/envs/project-implicit/include -mmacosx-version-min=10.9 -m64 -fPIC -I/Users/nityansuman/anaconda3/envs/project-implicit/include -mmacosx-version-min=10.9 -m64 -fPIC -I/Users/nityansuman/anaconda3/envs/project-implicit/include/python3.6m -I/private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-sudm1p9g/include -I/Users/nityansuman/anaconda3/envs/project-implicit/include/python3.6m -c en_coref_sm/neuralcoref/neuralcoref.cpp -o build/temp.macosx-10.9-x86_64-3.6/en_coref_sm/neuralcoref/neuralcoref.o
    In file included from en_coref_sm/neuralcoref/neuralcoref.cpp:4:
    In file included from /Users/nityansuman/anaconda3/envs/project-implicit/include/python3.6m/Python.h:25:
    /Users/nityansuman/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/nityansuman/anaconda3/envs/project-implicit/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-sudm1p9g/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-record-c2wxcm2q/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0p/gsfhfkcj45525788hzflpnqr0000gn/T/pip-req-build-sudm1p9g/

OS: MacOs Mojave
Python: 3.6

**Comment by cbjrobertson** [comment]
Why is this closed with no solution? I am experiencing the same issue...
