### ISSUE TITLE
I created a raspberry pi image

### ISSUE THREAD

**Issue by boehm-e** [huggingface/neuralcoref#107]
Hi, 
if anyone is interested, I create a Raspberry Pi image with 
en_coref_sm installed (with spacy, and en_core_web_sm) , ready to go:

to download it : https://drive.google.com/file/d/1swM9xNzCGpFat2o3iK_CiM8tm4rhFwj8/view?usp=sharing

The image is based on https://github.com/bamarni/pi64/ , a 64bit linux for raspberry pi :
currently tested on PI 3B+ (2017) but should work on all raspberry pi 3.

**Comment by thomwolf** [comment]
That's very cool!
The new version (4.0) has a smaller model since we are now independent of SpaCy models.
Feel free to tell me if you try to convert it and experience issues with a R-Pi.
