### ISSUE TITLE
Get resolved doc

### ISSUE THREAD

**Issue by cyclecycle** [huggingface/neuralcoref#109]
Is there a recommended way to get a coref resolved Doc object?

Reprocessing the resolved text to create a new Doc works but is not the most efficient.

Thanks

**Comment by thomwolf** [comment]
I don't think there is any clean way to modify the tokens of a SpaCy Doc once it has been tokenized so unfortunately your method is probably the simplest one.

You may want to open an issue on SpaCy's github if this is a serious issue.
