### ISSUE TITLE
Usage of contextualized embeddings?

### ISSUE THREAD

**Issue by JoanEspasa** [huggingface/neuralcoref#111]
Good afternoon,

First at all, congrats on the nice implementation! The demo is beautiful :smile: 

I have two small questions:
* I was skimming through the posts/articles and wondering if maybe using ELMo/Flair/BERT embeddings could replace in some sense the few manually created features for the model, or at least improve the results slightly?

* I am only interested in coreferences of some entities for which I retrained a NER model. What is the best way to get only the mentions to those entities? Run neuralcoref and then filter the chains of coreferences that do not appear on the NER output?

Thanks for your insights :+1:

**Comment by thomwolf** [comment]
Hi, here are some answers:
- using ELMo/Flair/BERT: yes probably :)
- filtering: yes I think filtering is the easiest way to do it.
