### ISSUE TITLE
The training instructions no longer correspond to the actual package structure

### ISSUE THREAD

**Issue by eduardbarbu** [huggingface/neuralcoref#119]
I'm trying to train a model (with Conll and Ontonotes files) using the instructions from  : https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md

Unfortunately the current code doesn't reflect those instructions. In the first place the conllparser.py module is now under "train" directory so : python -m neuralcoref.conllparser ...command fails.
Secondly, after I move all the files back in "neuralcoref" and execute the training command this fails with the error : 
self._extract_mentions(parsed, len(self.utterances), self.n_sents, self.speakers[speaker_id])
AttributeError: 'ConllDoc' object has no attribute '_extract_mentions'
Indeed the class ConllDoc has no such attribute.
 Is it still possible to create a model? And if yes how?

Thanks!
Eduard

**Comment by thomwolf** [comment]
Yes, updating the training scripts is my next to-do.
