### ISSUE TITLE
spaCy version

### ISSUE THREAD

**Issue by kleinias** [huggingface/neuralcoref#12]
As written in the readme at "If you are an early user of spacy 2 alpha --- (and there is now spacy 2.0.6 and the version won't be lower in the future, and you could adress the project by typing its proper name with big C) ---  , you can use neuralcoref with spacy 2 without any specific modification", there should be no problem with spaCy 2 using appropriate models. Instead of this iInstalling the requirements of neuralcoref overwrites and corrupts an exisiting installation of spacy. So please update your readme directing to a working version of spaCy or upgrade your own version.

**Comment by thomwolf** [comment]
You are right, there is currently an incompatibility with spacy 2 (which is different than the alpha version I was using). I will update it to be compatible with spacy 2 next week.

**Comment by Robert923** [comment]
Awesome, thank you @thomwolf !  :-)

**Comment by kleinias** [comment]
Your plan is really nice. 
Are you going to do this this week?

**Comment by julien-c** [comment]
Closing this as it should now be fixed, feel free to reopen otherwise

**Comment by kleinias** [comment]
It works, thank you!
