### ISSUE TITLE
Load problems, SystemError: Missing type object

### ISSUE THREAD

**Issue by rkingery** [huggingface/neuralcoref#122]
Hey, like many others on here, I'm having a world of issues trying to get this library to run on macOS Mojave. My python version is 3.6, via Anaconda. On top of the cython issues mentioned in #97 (which I sort of found a work-around for), I'm getting errors when trying to load the nlp models, even inside the conda env trick mentioned in #116. The errors I'm getting are shown below. Any fixes would be helpful. Thanks.

![image](https://user-images.githubusercontent.com/29710965/50290973-404ed300-043b-11e9-904b-526c88f705da.png)

**Comment by qhungngo** [comment]
I also had this issue when using spaCy 2.0.18

**Comment by thomwolf** [comment]
This should be fixed in the new release (4.0)
