### ISSUE TITLE
Model install error with spaCy 2.0.18

### ISSUE THREAD

**Issue by folterj** [huggingface/neuralcoref#123]
Installing coref model using pip3 (Python 3.6) with spaCy 2.0.18 fails with below error message.

- OS: Centos 7
- Python: 3.6
- spaCy: 2.0.18

Installation error message (after downloading model file):

Complete output from command python setup.py egg_info:
error in en_coref_lg setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in spacy>=>=2.0.0a18 at >=>=2.0.0a18

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-ubayjf65/

**Comment by thomwolf** [comment]
This should also be fixed in the new release (4.0).
Please open a new issue if it's not the case.
