### ISSUE TITLE
fast continuous coreference

### ISSUE THREAD

**Issue by boehm-e** [huggingface/neuralcoref#124]
Hi, 
In older neuralcoref releases we could use something like that:
```python
coref.one_shot_coref(utterances="It is now walking", context="The bird is flying")
```

and we would have **It** as a mention of **bird**

I am working with speech recognition, so i need to analyze continuous sentences:
So : 
- is there a clean way to do it with the current release ?
- is there a function like the previous **continuous_coref** ?

I know I could do it myself by passing the whole text from the beginning every time a new sentence arrive. But it is really not efficient. That's why I'm asking if there is a cleaner / faster way of doing that.

Thank you for this awesome Lib

**Comment by thomwolf** [comment]
Hi,
This use to be necessary when we where using a python slow code. The cython code is a lot faster so continuous coreference make a lot less sense. It's also a lot more difficult to do now that we are tightly integrated with SpaCy.
I don't think we will add this feature back (but feel free to open a PR if you want to give it a go).
