### ISSUE TITLE
Any plans to make neuralcoref avaliable on PyPI?

### ISSUE THREAD

**Issue by JohnGiorgi** [huggingface/neuralcoref#129]
Hi,

First of thanks for the tool! I was just wondering if there were any plans to stick `neuralcoref` on PyPI?

I have uploaded [My own project](https://github.com/BaderLab/saber) to PyPI, but because it depends on `en-coref-md`, trying to install it with `pip install` throws the following error:

```
Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
saber depends on en-coref-md @ https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_md-3.0.0/en_coref_md-3.0.0.tar.gz
```

Alternatively, if anyone knows install packages on PyPI with direct dependencies I would love to hear it, thanks!

**Comment by thomwolf** [comment]
The latest release (4.0) is now on PyPI

**Comment by JohnGiorgi** [comment]
Awesome, thanks!
