### ISSUE TITLE
Got a problem while installing

### ISSUE THREAD

**Issue by mihirsaxena** [huggingface/neuralcoref#13]
Got this error while installing it on my virtual environment: "Permission denied: '/Library/Python/2.7/site-packages/certifi' " It also deleted my nltk files from the virtual environment. Please guide me where's the problem.

**Comment by thomwolf** [comment]
You are right, there is currently an incompatibility with the new spacy 2 which is a bit different than the alpha version. I will update it to be compatible with spacy 2 next week.

**Comment by thomwolf** [comment]
Ok this should be fixed, I updated the repo and the installation instruction. Can you check it is working for you now ?

**Comment by julien-c** [comment]
Closing this as it should now be fixed, feel free to reopen otherwise
