### ISSUE TITLE
'ConllDoc' object has no attribute '_extract_mentions' error

### ISSUE THREAD

**Issue by pdhung3012** [huggingface/neuralcoref#131]
I already had problem with neuralcoref.conllparser not found module, however, I overcame this challenge by fix directly the python file and run directly the python file.

When I ran the conllparser.py file, I continued to have this error. I have checked and see that there is no definition of the extract_mention method in ConllDoc class. The code seems to incomplete I guess.

Parsing utterances and filling docs
  0%|                                                | 0/238192 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "conllparser.py", line 711, in <module>
    CORPUS.read_corpus(args.path)
  File "conllparser.py", line 618, in read_corpus
    use_gold_mentions=self.use_gold_mentions)
  File "conllparser.py", line 318, in add_conll_utterance
    self._extract_mentions(parsed, len(self.utterances), self.n_sents, self.speakers[speaker_id])
AttributeError: 'ConllDoc' object has no attribute '_extract_mentions'

**Comment by pdhung3012** [comment]
I tried solution that replace extract_mentions by process_mentions of Document.py. Hope it works

**Comment by thomwolf** [comment]
The training scripts are currently out-dated. I'm closing this for now as there are already many issues open on training (and I'll probably completely refactor the training scripts when I'll update them).
