### ISSUE TITLE
coref_clusters

### ISSUE THREAD

**Issue by SagarJHedau** [huggingface/neuralcoref#132]
While executing project i am facing the following issue please help ? I have attached my screen shot for reference 

python3 corefrence.py 
My sister has a dog. She loves him
Traceback (most recent call last):
  File "corefrence.py", line 6, in <module>
    b = doc._.coref_clusters
  File "/Users/shahsamad/Desktop/Angular4/pythonProj/env/lib/python3.7/site-packages/spacy/tokens/underscore.py", line 28, in __getattr__
    raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_clusters'. Did you forget to call the `set_extension` method?
(env) Shahs-Mac-mini:pythonProj shahsamad$ 
![screen shot 2019-02-05 at 8 40 25 pm](https://user-images.githubusercontent.com/46328309/52282382-4f0b2e00-2986-11e9-8ead-b0d65c36cbe8.png)

**Comment by zou-longkun** [comment]
I have encountered the same problem, but I don't know how to modify it. Have you solved it? Can you teach me?

**Comment by zou-longkun** [comment]
I have solved this issue. Just reinstall the 'MODEL_URL' , try :
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz

**Comment by thomwolf** [comment]
This should be fixed in the latest release (4.0)

**Comment by aamin3** [comment]
Same, I'm having this issue exclusively in Jupyter Notebook but note in Pycharm

**Comment by svlandeg** [comment]
I haven't run into this specific issue myself, and the fact that it works in PyCharm does suggest a problem with your virtual environment in your notebook. Can you make sure it's running from the correct venv? Have you tried restarting your kernel etc? I sometimes have issues with Jupyter with other libraries, and restarting 3 times sometimes helps :|

**Comment by aamin3** [comment]
Yes I fixed I apologize...simply copied code incorrectly...

**Comment by svlandeg** [comment]
No worries, thanks for letting us know!
