### ISSUE TITLE
Coreferring noun phrases

### ISSUE THREAD

**Issue by AugustIgner** [huggingface/neuralcoref#135]
Hi,

Thank you for this tool, it's awesome.
I was wondering, is it able to detect coreferring noun phrases?
I could not find any information about this.

I tried running this example from Wikipedia:
- "The project leader is refusing to help. The jerk thinks only of himself."

"The project leader" refers to "The jerk", but a reference is not present in the output.

I would appreciate any details about the subject

**Comment by thomwolf** [comment]
Maybe we should add a debug feature to extract the mentions and scores even when a co-reference is not detected. I'll give a try in a future release.
