### ISSUE TITLE
AttributeError: [E046] Can't retrieve unregistered extension attribute 'has_coref'. 

### ISSUE THREAD

**Issue by zou-longkun** [huggingface/neuralcoref#137]
Hello, While executing project I am facing the following issue please help ?
File "test.py", line 6, in <module>
    print(doc._.has_coref)                      
  File "C:\Users\Longkun\Anaconda3\lib\site-packages\spacy\tokens\underscore.py", line 28, in __getattr__
    raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'has_coref'. Did you forget to call the `set_extension` method?

**Comment by zou-longkun** [comment]
I have solved this issue. Just reinstall the 'MODEL_URL' , try :
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz

**Comment by thomwolf** [comment]
Hi, this  should be fixed in the latest release (4.0) and with SpaCy 2.1+
Feel free to open a new issue if you still experience issues.

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by rockinthespecs** [comment]
I am having the same issue. 
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the `set_extension` method?

**Comment by poglesbyg** [comment]
I am having the same issue.
raise AttributeError(Errors.E046.format(name=name))
AttributeError: [E046] Can't retrieve unregistered extension attribute 'coref_resolved'. Did you forget to call the set_extension method?

**Comment by pz325** [comment]
Hi, having the same issue: 

neuralcoref            4.0
spacy                  2.2.4
