### ISSUE TITLE
File "neuralcoref.pyx", line 101, in init en_coref_sm.neuralcoref.neuralcoref TypeError: must be char, not unicode

### ISSUE THREAD

**Issue by akshayakp97** [huggingface/neuralcoref#141]
I am using 
Python 2.7 
neuralcoref 3.1
spacy 2.0.12
thinc 6.10.3

MacOS High Sierra 10.13.4 
I tried with both 'en_coref_sm' and 'en_coref_md'.

I tried switching spacy versions also. (To 2.0.18 and 2.0.13). 
I have been getting errors such as "ValueError: cymem.cymem.Pool has the wrong size, try recompiling. Expected 64, got 48"
and
"ValueError: spacy.strings.StringStore has the wrong size, try recompiling. Expected 88, got 112"

Thanks in advance.

**Comment by kartikeyaSh** [comment]
@akshayakp97 ```pip install spacy==2.0.13``` got it to work.
for more refer this issue : https://github.com/huggingface/neuralcoref/issues/102

**Comment by thomwolf** [comment]
Hi, these installation issue should be fixed in the latest release (4.0) and with SpaCy 2.1+
Feel free to open a new issue if you still experience installation problems.

**Comment by akshayakp97** [comment]
The latest version works. 
Thanks!

**Comment by saurabhhjjain** [comment]
Latest version is not working. I got following error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/saurabh/neuralcoref/neuralcoref/__init__.py", line 14, in <module>
    from .neuralcoref import NeuralCoref
  File "neuralcoref.pyx", line 111, in init neuralcoref.neuralcoref
TypeError: must be char, not unicode
