### ISSUE TITLE
Clarify in the docs how to get 'en_coref_sm' which is in your server.py example?

### ISSUE THREAD

**Issue by arnicas** [huggingface/neuralcoref#150]
It seems that python -m spacy download en_coref_sm doesn't install the neural coref model... and the server.py example just fails without any info on this.  Probably just needs a doc line in the README about what to do here?

Thanks, Lynn

**Comment by thomwolf** [comment]
Oh you are right, the `server.py` example is out-dated now.
I'll update it to be compatible with NeuralCoref 4.0

**Comment by thomwolf** [comment]
Ok this is fixed now, and I've added a more detailed section on using `server.py` in the readme [here](https://github.com/huggingface/neuralcoref#using-neuralcoref-as-a-server).
