### ISSUE TITLE
Possessive pronouns

### ISSUE THREAD

**Issue by eukaryote31** [huggingface/neuralcoref#151]
Right now, possessive pronouns aren't resolved very well:

For example:
```
John walked in his house. 
```
Results in:
```
John walked in John house.
```

**Comment by thomwolf** [comment]
Actually, "resolving" is an ill-defined operation and has no really good answer (in particular in terms of identifying a mention that could be used to replace all other mentions).
It's provided as a way to extract a simple result from NeuralCoref as a string but the coreference clusters are the real output of the algorithm.
