### ISSUE TITLE
How to move to pip release from using old downloaded model?

### ISSUE THREAD

**Issue by swartchris8** [huggingface/neuralcoref#153]
So I am looking for a way to pip install `neuralcoref` with spacy 2.0.x

Currently I am using the old 3.0.0 coref lg pretrained spacy model https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_lg-3.0.0/en_coref_lg-3.0.0.tar.gz

I would like to move the pip version of neuralcoref 3.0.0 due to coming across `spacy.strings.StringStore size changed, may indicate binary incompatibility` issue described in the README.

Following the 4.0.0 README I tried
```
pip install spacy==2.0.13 
pip install neuralcoref==3.1
```

Then tried to follow the README neuralcoref initialisation and came across the `  File "neuralcoref.pyx", line 854, in neuralcoref.neuralcoref.NeuralCoref.get_static
  File "vectors.pyx", line 116, in spacy.vectors.Vectors.__getitem__
KeyError: 77186543510594498` which is fixed in 4.0.0 according to this issue https://github.com/huggingface/neuralcoref/issues/98 is there any way to get around this issue while staying on spacy 2.0.x?

It seems to me `neuralcoref==3.9` depends on spacy 2.1 so that isn't an option.

**Comment by thomwolf** [comment]
Hi @swartchris8, we don't plan to keep compatibility with SpaCy 2.0 as it's dependency structure was the source of most installation issues to arise in the last months and SpaCy 2.1 is a lot easier to handle.

NeuralCoref 4.0 is also a major update of NeuralCoref 3.0 so you won't be able to mix the model of one with the code of the other.

What happens when you follow the instructions of installation [here](https://github.com/huggingface/neuralcoref#spacystringsstringstore-size-changed-error)?

**Comment by swartchris8** [comment]
Following the `pip install neuralcoref` instructions from the current README leads me to this error:

`File "neuralcoref.pyx", line 854, in neuralcoref.neuralcoref.NeuralCoref.get_static File "vectors.pyx", line 116, in spacy.vectors.Vectors.__getitem__ KeyError: 77186543510594498`

which you seem to have fixed in `4.0.0` based on this issee #98

**Comment by thomwolf** [comment]
What os, version of python and spacy are you using?

**Comment by swartchris8** [comment]
This was in a python:2.7.16-jessie Docker image with spacy==2.0.13

**Comment by thomwolf** [comment]
Ok, I'm afraid I can't really help you more since we've droped compatibility with spacy 2.0...
If you happened to find a work-around you can share here as it might help others.

Out of curiosity, what is preventing you from moving to SpaCy 2.1?

**Comment by swartchris8** [comment]
Long story short we have some dependencies on a 2.0.x and I thought we might need to stay on 2.0 due to some weird Python 2 unicode width requirements.
