### ISSUE TITLE
SystemError: [E130] You are running a narrow unicode build, which is incompatible with spacy >= 2.1.0. To fix this, reinstall Python and use a wide unicode build instead. You can also rebuild Python and set the --enable-unicode=ucs4 flag.

### ISSUE THREAD

**Issue by MHDBST** [huggingface/neuralcoref#155]
I have installed NeuralCoref using --no-binary command, when I want to use it inside the Jupiter in version 3 I get the following error:

SystemError: [E130] You are running a narrow unicode build, which is incompatible with spacy >= 2.1.0. To fix this, reinstall Python and use a wide unicode build instead. You can also rebuild Python and set the --enable-unicode=ucs4 flag.

How can I solve this issue?

**Comment by thomwolf** [comment]
Can you use a python 3 kernel?

**Comment by MHDBST** [comment]
@thomwolf I had to remove everything and reinstall python3, the problem solved.
