### ISSUE TITLE
Failed building wheel for en-coref-md

### ISSUE THREAD

**Issue by LaplandSnowy** [huggingface/neuralcoref#161]
pip install en_coref_md-3.0.0.tar.gz
Processing c:\users\cher\desktop\en_coref_md-3.0.0.tar.gz
Requirement already satisfied: spacy>=>=2.0.0 in c:\users\cher\anaconda3\lib\site-packages (from en-coref-md==3.0.0) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (2.21.0)
Requirement already satisfied: wasabi<1.1.0,>=0.2.0 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (0.2.2)
Requirement already satisfied: preshed<2.1.0,>=2.0.1 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (2.0.1)
Requirement already satisfied: plac<1.0.0,>=0.9.6 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (0.9.6)
Requirement already satisfied: thinc<7.1.0,>=7.0.2 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (7.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (1.0.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (2.0.2)
Requirement already satisfied: jsonschema<3.0.0,>=2.6.0 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (2.6.0)
Requirement already satisfied: blis<0.3.0,>=0.2.2 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (0.2.4)
Requirement already satisfied: srsly<1.1.0,>=0.0.5 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (0.0.5)
Requirement already satisfied: numpy>=1.15.0 in c:\users\cher\anaconda3\lib\site-packages (from spacy>=>=2.0.0->en-coref-md==3.0.0) (1.16.2)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\cher\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0->en-coref-md==3.0.0) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\cher\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0->en-coref-md==3.0.0) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cher\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0->en-coref-md==3.0.0) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\cher\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy>=>=2.0.0->en-coref-md==3.0.0) (3.0.4)
Requirement already satisfied: tqdm<5.0.0,>=4.10.0 in c:\users\cher\anaconda3\lib\site-packages (from thinc<7.1.0,>=7.0.2->spacy>=>=2.0.0->en-coref-md==3.0.0) (4.31.1)
Building wheels for collected packages: en-coref-md
  Building wheel for en-coref-md (setup.py) ... error
  Complete output from command C:\Users\Cher\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Cher\\AppData\\Local\\Temp\\pip-req-build-s00u6uwv\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Cher\AppData\Local\Temp\pip-wheel-oucmvxi8 --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\en_coref_md
  copying en_coref_md\__init__.py -> build\lib.win-amd64-3.7\en_coref_md
  creating build\lib.win-amd64-3.7\en_coref_md\neuralcoref
  copying en_coref_md\neuralcoref\__init__.py -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
  copying en_coref_md\__init__.pxd -> build\lib.win-amd64-3.7\en_coref_md
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0
  copying en_coref_md\en_coref_md-3.0.0\meta.json -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0
  copying en_coref_md\en_coref_md-3.0.0\tokenizer -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
  copying en_coref_md\en_coref_md-3.0.0\ner\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
  copying en_coref_md\en_coref_md-3.0.0\ner\lower_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
  copying en_coref_md\en_coref_md-3.0.0\ner\moves -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
  copying en_coref_md\en_coref_md-3.0.0\ner\tok2vec_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
  copying en_coref_md\en_coref_md-3.0.0\ner\upper_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\pairs_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\single_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors\key2row -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors\vectors -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors\key2row -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors
  copying en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors\vectors -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
  copying en_coref_md\en_coref_md-3.0.0\parser\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
  copying en_coref_md\en_coref_md-3.0.0\parser\lower_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
  copying en_coref_md\en_coref_md-3.0.0\parser\moves -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
  copying en_coref_md\en_coref_md-3.0.0\parser\tok2vec_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
  copying en_coref_md\en_coref_md-3.0.0\parser\upper_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
  copying en_coref_md\en_coref_md-3.0.0\tagger\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
  copying en_coref_md\en_coref_md-3.0.0\tagger\model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
  copying en_coref_md\en_coref_md-3.0.0\tagger\tag_map -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
  creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
  copying en_coref_md\en_coref_md-3.0.0\vocab\key2row -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
  copying en_coref_md\en_coref_md-3.0.0\vocab\lexemes.bin -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
  copying en_coref_md\en_coref_md-3.0.0\vocab\strings.json -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
  copying en_coref_md\en_coref_md-3.0.0\vocab\vectors -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
  copying en_coref_md\meta.json -> build\lib.win-amd64-3.7\en_coref_md
  copying en_coref_md\neuralcoref\neuralcoref.pyx -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
  copying en_coref_md\neuralcoref\neuralcoref.pxd -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
  copying en_coref_md\neuralcoref\__init__.pxd -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
  running build_ext
  building 'en_coref_md.neuralcoref.neuralcoref' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

  ----------------------------------------
  Failed building wheel for en-coref-md
  Running setup.py clean for en-coref-md
Failed to build en-coref-md
Installing collected packages: en-coref-md
  Running setup.py install for en-coref-md ... error
    Complete output from command C:\Users\Cher\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Cher\\AppData\\Local\\Temp\\pip-req-build-s00u6uwv\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Cher\AppData\Local\Temp\pip-record-q775kop7\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\en_coref_md
    copying en_coref_md\__init__.py -> build\lib.win-amd64-3.7\en_coref_md
    creating build\lib.win-amd64-3.7\en_coref_md\neuralcoref
    copying en_coref_md\neuralcoref\__init__.py -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
    copying en_coref_md\__init__.pxd -> build\lib.win-amd64-3.7\en_coref_md
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0
    copying en_coref_md\en_coref_md-3.0.0\meta.json -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0
    copying en_coref_md\en_coref_md-3.0.0\tokenizer -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
    copying en_coref_md\en_coref_md-3.0.0\ner\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
    copying en_coref_md\en_coref_md-3.0.0\ner\lower_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
    copying en_coref_md\en_coref_md-3.0.0\ner\moves -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
    copying en_coref_md\en_coref_md-3.0.0\ner\tok2vec_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
    copying en_coref_md\en_coref_md-3.0.0\ner\upper_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\ner
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\pairs_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\single_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors\key2row -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors\vectors -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\static_vectors
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors\key2row -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors
    copying en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors\vectors -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\neuralcoref\tuned_vectors
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
    copying en_coref_md\en_coref_md-3.0.0\parser\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
    copying en_coref_md\en_coref_md-3.0.0\parser\lower_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
    copying en_coref_md\en_coref_md-3.0.0\parser\moves -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
    copying en_coref_md\en_coref_md-3.0.0\parser\tok2vec_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
    copying en_coref_md\en_coref_md-3.0.0\parser\upper_model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\parser
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
    copying en_coref_md\en_coref_md-3.0.0\tagger\cfg -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
    copying en_coref_md\en_coref_md-3.0.0\tagger\model -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
    copying en_coref_md\en_coref_md-3.0.0\tagger\tag_map -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\tagger
    creating build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
    copying en_coref_md\en_coref_md-3.0.0\vocab\key2row -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
    copying en_coref_md\en_coref_md-3.0.0\vocab\lexemes.bin -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
    copying en_coref_md\en_coref_md-3.0.0\vocab\strings.json -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
    copying en_coref_md\en_coref_md-3.0.0\vocab\vectors -> build\lib.win-amd64-3.7\en_coref_md\en_coref_md-3.0.0\vocab
    copying en_coref_md\meta.json -> build\lib.win-amd64-3.7\en_coref_md
    copying en_coref_md\neuralcoref\neuralcoref.pyx -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
    copying en_coref_md\neuralcoref\neuralcoref.pxd -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
    copying en_coref_md\neuralcoref\__init__.pxd -> build\lib.win-amd64-3.7\en_coref_md\neuralcoref
    running build_ext
    building 'en_coref_md.neuralcoref.neuralcoref' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "C:\Users\Cher\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Cher\\AppData\\Local\\Temp\\pip-req-build-s00u6uwv\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Cher\AppData\Local\Temp\pip-record-q775kop7\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Cher\AppData\Local\Temp\pip-req-build-s00u6uwv\

Win 10
Python 3.7

I do have VS C++ 14

Thanks for your attention!

**Comment by thomwolf** [comment]
You should switch to the new version 4.0 (see the readme).

**Comment by LaplandSnowy** [comment]
Thanks so much! It's working now!

**Comment by thomwolf** [comment]
Happy to hear that!

**Comment by sy178sy** [comment]
(myenv) C:\Python38\mycal\project>pip install en_coref-4.0.0.tar.gz
Processing c:\python38\mycal\project\en_coref-4.0.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\HP\Anaconda3\envs\myenv\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-req-build-41upqyhk\\setup.py'"'"'; __file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-req-build-41upqyhk\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\HP\AppData\Local\Temp\pip-pip-egg-info-uxsh4qb8'
         cwd: C:\Users\HP\AppData\Local\Temp\pip-req-build-41upqyhk\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\Anaconda3\envs\myenv\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-req-build-41upqyhk\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


Facing this error here while downloading
