### ISSUE TITLE
Segmentation Fault: neuralcoref==0.4.0 & spacy==2.1.4

### ISSUE THREAD

**Issue by dmmiller612** [huggingface/neuralcoref#164]
Hello, first of all, I wanted to mention that this is an awesome library. I am building a library around both this repository and your BERT implementations for extractive text summarization.

I recently noticed that I am getting a segmentation fault with spacy==2.1.4 and neuralcoref==0.4.0. I have tried this on ubuntu 18.04 and macOS. Spacy==2.1.3 seems to be working fine. The code below reproduces the issue.

```
import neuralcoref
from spacy.lang.en import English

nlp = English()
nlp.add_pipe(self.nlp.create_pipe('sentencizer'))
neuralcoref.add_to_pipe(nlp, greedyness=0.4)
```

I was going to take a look at this issue myself, but I wanted to make sure that you hadn't ran across something like this beforehand.

**Comment by mdrago98** [comment]
Is this issue reproduced in spacy 2.13?

**Comment by dmmiller612** [comment]
As an update, spacy 2.1.3 does not have an issue and works fine. I have only seen the issue in spacy==2.1.4

**Comment by SrGrace** [comment]
its not even working with spacy==2.1.3. Segmentation fault :(

**Comment by mmxgn** [comment]
I think this is a duplicate of: https://github.com/huggingface/neuralcoref/issues/167

Neuralcoref (4.0 - from pip) works with 2.1.3 here.

**Comment by SrGrace** [comment]
Yeah, I created a new venv and then installed it with spacy==2.1.3. working fine!

**Comment by colby-ham** [comment]
I also was able to get it working using spacy==2.1.3

**Comment by thomwolf** [comment]
Yeah, this is a recurring problem.
I would like to be able to understand how we could keep the library in sync with SpaCy more easily.
I'll see if Matthew and Inès have some insights.

**Comment by cmckain** [comment]
Recompilation from source after installing spacy was able to solve this problem for me, even on 2.1.6.

![image](https://user-images.githubusercontent.com/21251762/61178761-c33aa500-a5a8-11e9-8905-6e75501aef9b.png)

**Comment by svlandeg** [comment]
Merging with Issue #197
