### ISSUE TITLE
Getting error while creating doc, post adding neuralcoref to the spacy pipeline in Windows.

### ISSUE THREAD

**Issue by sairaza** [huggingface/neuralcoref#166]
Python : 3.7
Spacy Version : 2.1.4,
neuralcoref version : 4.0,

import spacy
import neuralcoref
nlp = spacy.load('en_core_web_sm')
neuralcoref.add_to_pipe(nlp)
doc = nlp(u"My sister has a dog. She loves him")

While running this code on Spyder, kernel is getting killed when executing the last line.
 
Exact Error:
An error ocurred while starting the kernel
May 30, 2019 3:29:04 PM 
org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO: To get higher rendering speed on JDK8 or later,
May 30, 2019 3:29:04 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO: use the option 

Please help.

**Comment by pHequals7** [comment]
Exact problem, everytime I add neuralcoref to my spaCy pipeline, my kernel dies and have to restart from scartch. Kindly look into this. I'm running Python 3.7, spaCy 2.1 and the latest neuralcoref version

**Comment by amandalmia14** [comment]
@pHequals7 Did you get any workaround ?

**Comment by pHequals7** [comment]
Unfortunately no :/

**Comment by harelhan** [comment]
I am also facing the same issue. Please help!

**Comment by svlandeg** [comment]
Could you check whether you're still encountering this behaviour when you downgrade spaCy to 2.1.0 ?

Alternatively, if you need a newer version of spaCy, install that first and then [build neuralcoref from source](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source). Does that solve the issue?

**Comment by amandalmia14** [comment]
@svlandeg Its working perfectly on spaCy to 2.1.0. 

I didn't build, so can't comment on that.

**Comment by ewindchung** [comment]
I have the same problem. spaCy 2.1.8. python 3.7

**Comment by amandalmia14** [comment]
@ewindchung It works perfectly on 2.1.0 version of spaCy  on python 3.7 environment.

**Comment by svlandeg** [comment]
Merging with Issue #197

**Comment by amandalmia14** [comment]
@svlandeg Thanks for merging :)

**Comment by ewindchung** [comment]
@amandalmia14 Thanks. It works perfectly now.
