### ISSUE TITLE
Python stopped Working

### ISSUE THREAD

**Issue by RandomForestGump** [huggingface/neuralcoref#167]
Hi,

I am a windows 10 user,  working on spacy 2.1.4 with english web-lg model(v2.1.0)
After adding neuralcoref to pipeline, I am getting a Python stopped working error as soon as I parse.

Wanted to know what is causing this error.

**Comment by codewpf** [comment]
I have a some issue, but my code enviroment is macOS  and spacy 2.1.4 with en_core_web_sm. The python crashed when I run the sample code which crashed on 'neuralcoref.add_to_pipe(nlp)'.

**Comment by liu357592109** [comment]
Same issue with macOS and spacy 2.1.4.  The error message is "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

**Comment by mmxgn** [comment]
Same issue with SpaCy 2.1.4 and linux (python=3.7.3). Kernel gets restarted as soon as I try to parse a sentence.

**Comment by LukasHaas** [comment]
Same issue with JupyterNotebook. Kernel gets restarted after parsing a sentence. Model ‘en’ works fine without neuralcoref.

**Comment by taku-ito** [comment]
It worked after changing the Spacy's version to 2.1.0

**Comment by mmxgn** [comment]
It also works for Spacy 2.1.3. Seems 2.1.4 is the one causing the problems. Any advise on how to debug it?

**Comment by gorqkop** [comment]
Same with Spacy 2.1.8

**Comment by mmxgn** [comment]
Installing neuralcoref from source fixed it for me using Spacy 2.1.8

**Comment by svlandeg** [comment]
Thanks for the reports. For now the workaround is indeed to either downgrade spaCy, or to install neuralcoref from source. In the future, we'll try to keep this plugin more in-sync with spaCy, cf Issue #197.

**Comment by davidbernat** [comment]
It appears this is now a problem again with Spacy 2.2.2 and Coref 4.0?

**Comment by sqlmonk** [comment]
I am facing the same issue.
Name: spacy Version: 2.3.2
Name: neuralcoref Version: 4.0

How ot fix it.

**Comment by svlandeg** [comment]
Have you tried installing neuralcoref from source?

**Comment by mustafaKus** [comment]
Any other solutions on that. It seems installing from source use python 2 in cythonizer. We are using cythonizer 3 in our codebase. So I am not able to install from source.

**Comment by mustafaKus** [comment]
Is there any ETA for the solution on this issue. Will we be able to use neuralcoref on the pip servers in near future?
