### ISSUE TITLE
Neuralcoref is modifying Noun in text

### ISSUE THREAD

**Issue by KalidindiMounika** [huggingface/neuralcoref#169]
Neuralcoref is modifying the Noun in the below sentence. 
In the below example Valli is modified to prasanna. There are many such scenarios.
 
Input : weather in chennai. I want author Prasanna book. I want author Valli book.
Output: weather in chennai. I want author Prasanna book. I want author Prasanna book.

Kindly help me out to resolve this issue.

**Comment by kjaquier** [comment]
Do you have a code snippet that reproduces the issue?

**Comment by KalidindiMounika** [comment]
Resolved the issue , Thank you
