### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by AmanYdv20** [huggingface/neuralcoref#171]
Everytime I tried to run my file it shows -
RuntimeWarning: spacy.tokens.span. Span size changed, may indicate binary incompatibity. Expected 72 from C header, got 80 from PyObject
Return f(*args, **kwds)
Segmentation fault

Though I have tried both the way as listed for the installation.

**Comment by talbaumel** [comment]
Same here
OS windows 10
Python 3.7.1
PyTorch 1.0,1

**Comment by rinaldo-rex** [comment]
Have you tried [this?](https://github.com/huggingface/neuralcoref#spacystringsstringstore-size-changed-error)

I suppose this is the documented error mentioned there. 

``` 
pip uninstall neuralcoref
pip install neuralcoref --no-binary neuralcoref
```

**Comment by talbaumel** [comment]
Thanks, but didn't work for me 😔

**Comment by rinaldo-rex** [comment]
@talbaumel You may have to reinstall spacy along with Neuralcoref. Try with a lower set of versions please? There are issues with recent versions of Spacy with Neuralcoref. Let us know your versions too, so it's easier for others to pitch in. 🙂

Tried and tested: 
Python **3.6.8**
spacy **2.1.3** (Note that 2.1.4 is causing the issues #164 )
neuralcoref **4.0.0**

**Comment by talbaumel** [comment]
spacy version was **2.1.4**
And 2.1.3 is working fine

Thank you!!

**Comment by rinaldo-rex** [comment]
Awesome! I think this can be marked as **duplicate of** #164 and closed. 🙂

**Comment by AmanYdv20** [comment]
Yeah mine started working with spacy 2.1.0. Thanks
