### ISSUE TITLE
Getting the relation between the plural object and its individual

### ISSUE THREAD

**Issue by HagerHosny199** [huggingface/neuralcoref#176]
I have a problem with this example:

<pre>
Input: "There are two beds. The first bed is in one corner. The second bed is in another corner."
Output:['The first bed in one corner', 'The second bed in another corner']
</pre>

It considers the first and the second bed as one object, so how to solve this problem ?

**Comment by svlandeg** [comment]
Thanks for the report! Merging with Issue #215
