### ISSUE TITLE
prepare the data fails 

### ISSUE THREAD

**Issue by dtsonov** [huggingface/neuralcoref#177]
When I run:
python -m conllparser --path /data/train/
the processing fails into the function: "build_and_gather_multiple_arrays"
inside which 'arrays' is empty and the output is:

array = np.stack(gathering_dict[feature])
File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 410, in stack
arrays = [asanyarray(arr) for arr in arrays]
TypeError: 'NoneType' object is not iterable

which is due to the empty arrays.

Has anyone faced this?

**Comment by svlandeg** [comment]
Hi @dtsonov, thanks for the report and sorry for the delay in answering.

We're currently fixing some of the pre-processing steps, cf. PR #213 and PR #211.
