### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by daniela-llivina** [huggingface/neuralcoref#18]
Should neuralconf work in some language other than English?

**Comment by julien-c** [comment]
Not right now, but we're working on releasing our model training code. What languages do you have in mind or do you have annotated coreference datasets available for them?

**Comment by daniela-llivina** [comment]
I need conference resolution for Spanish, unfortunately I do not have an annotated dataset.

**Comment by annkupriyanova** [comment]
Hi! I'm interested in training your model on the coreference corpus for Russian (http://rucoref.maimbava.net). When are you planning to release the model training code?

**Comment by thomwolf** [comment]
Within a week!

**Comment by thomwolf** [comment]
But @annkupriyanova you should note that spaCy currently [doesn't support Russian](https://spacy.io/models/) so you will have to find another parser and tweak the project to use it.

**Comment by julien-c** [comment]
Hi! I'm going to close this in favor of #2 so that the whole conversation around training is in the same place. Thanks!

**Comment by tutubalinaev** [comment]
> Hi! I'm interested in training your model on the coreference corpus for Russian (http://rucoref.maimbava.net). When are you planning to release the model training code?
HI @annkupriyanova, have you succeeded in training for Russian?
