### ISSUE TITLE
Can coref operate across multiple doc objects?

### ISSUE THREAD

**Issue by michelleful** [huggingface/neuralcoref#180]
I'm interested in applying neuralcoref iteratively as utterances are added to a conversation, as would be the case in a chatbot.

I've explored applying `coref.predict` to a list of `Doc`s, but that applies coreference to each individually, so that mentions aren't correlated across documents.

I'm currently reading through the Cython code to see if I can amend it, but thought I would ask first whether there's already some mechanism I'm overlooking for adding utterances without re-parsing the entire history of utterances over and over again.

Thank you!

**Comment by svlandeg** [comment]
I think the `doc` is the logical unit for processing, also in the core `spaCy` library you'd make predictions per `doc` and never across. The iterative adding of information from chatbots is an interesting use-case though. It would be cool if you could add sentences to a `doc` and tell the neural coref module to only parse those without prior annotations, but either way it's going to have to look back at the old sentences to find the heads of coreferent entities in the new sentences, right? Still, starting from partial information should speed up the processing and avoid doing all that work multiple times.

**Comment by michelleful** [comment]
I briefly looked at the Cython code back in July and based on that, thought that a viable approach might be to have a higher-order class which stores the coref clusters already found and whatever aspects of each entity in the coref cluster (or the last-mentioned entity in the coref cluster) are necessary to compute the feature vectors. 

Then for each new `Doc` extract the new entities and do the prediction against other entities in the doc AND existing coref clusters to either add them to an existing coref cluster or create a new coref cluster consisting only of that entity.

I'm not all that familiar with the codebase so this may not be the best approach though!
