### ISSUE TITLE
Multiple Subjects in Long Sentence Does Not Work

### ISSUE THREAD

**Issue by sachinkbarnwal** [huggingface/neuralcoref#181]
Mac OS: 10.14.5
Spacy: 2.1
NeuralCoreRef Version 4.0 

Code Snippet:

```
import spacy
import neuralcoref
nlp =  spacy.load('en_core_web_lg') # create blank Language class
print("Created blank en_core_web_lg")
coref = neuralcoref.NeuralCoref(nlp.vocab, conv_dict={'Admin': ['man']})
nlp.add_pipe(coref, name='neuralcoref')
nlp.get_pipe('neuralcoref').set_conv_dict({'Admin': ['man']})
doc=nlp("Doctor updated teachers. He modifies locations. Order is also modified by him. Admin creates report. He also updates report. The Customer steals money. He stole items as well.")
resolved = doc._.coref_resolved
print(doc._.has_coref)
print(doc._.coref_clusters)
print(resolved)
print(doc._.coref_clusters[0].mentions)
```

Output 
```
[Doctor: [Doctor, He, him, He, He]]
Doctor updated teachers. Doctor modifies locations. Order is also modified by Doctor. Admin creates report. Doctor also updates report. The Customer steals money. Doctor stole items as well.
[Doctor, He, him, He, He]
```

Expected Output:

`Doctor updated teachers. Doctor modifies locations. Order is also modified by Doctor. Admin creates report. Admin also updates report. The Customer steals money. The Customer stole items as well.
`
Please suggest

**Comment by tnmcneil** [comment]
I am having the same problem - For me it can differentiate between male and female gendered pronouns but if I introduce a second male it resolves it to the first reference.

ex with the same code and using doc._.coref_resolved on the following text:
```
Frodo is a small English golden retriever who loves to eat juicy red apples. 
He thinks they are delicious. 
His friend's name is Mary, she works in San Mateo. 
Jeremy is going to the market. He wants a sandwich.
```
I get the resolved output:

```
Frodo is a small English golden retriever who loves to eat juicy red apples. 
Frodo thinks they are delicious. 
Frodo friend's name is Mary, Mary works in San Mateo. 
Frodo is going to the market. Frodo wants a sandwich.
```
so not only does it resolve all male pronouns to Frodo, it actually resolves the new entity Jeremy to be Frodo as well.
Let me know if you have found some solution! I am thinking of pruning the coref relations on a higher coref score but I don't love that idea.

**Comment by svlandeg** [comment]
Thanks for the report! Merging with Issue #215.
