### ISSUE TITLE
Span.as_doc() doesn't keep coref_clusters

### ISSUE THREAD

**Issue by kjaquier** [huggingface/neuralcoref#182]
Code:
```python
nlp = spacy.load('en_core_web_sm')
coref = neuralcoref.NeuralCoref(nlp.vocab)
nlp.add_pipe(coref, name='neuralcoref')

doc = nlp("She loves him.")
print(len(doc._.coref_clusters), 'clusters')

doc = nlp("My sister has a dog. She loves him.")
print(len(doc._.coref_clusters), 'clusters')

doc = doc[7].sent.as_doc()
print(len(doc._.coref_clusters), 'clusters')
```
Output:
```
0 clusters
2 clusters
TypeError: object of type 'NoneType' has no len()
```
Expected:
```
0 clusters
2 clusters
0 clusters
```

**Comment by kjaquier** [comment]
Additionally, it might make sense in some cases to keep a reference to the clusters. Since it may introduce inconsistencies, maybe this could be enabled by a specific parameter, as follow:
Code:
```python
nlp = spacy.load('en_core_web_sm')
coref = neuralcoref.NeuralCoref(nlp.vocab, allow_outside_corefs=True)
nlp.add_pipe(coref, name='neuralcoref')

doc = nlp("She loves him.")
print(len(doc._.coref_clusters), 'clusters')

doc = nlp("My sister has a dog. She loves him.")
print(len(doc._.coref_clusters), 'clusters')

doc = doc[7].sent.as_doc()
print(len(doc._.coref_clusters), 'clusters')
print(doc[0].text, "=", doc[0].coref_clusters.main.text)
print(doc[2].text, "=", doc[2].coref_clusters.main.text)
```
Expected output:
```
0 clusters
2 clusters
2 clusters
She = My sister
him = a dog
```
I don't know how difficult it would be to implement though.

**Comment by svlandeg** [comment]
Thanks for the report @kjaquier ! Reopening this as this is functionality you'd expect to work. Might be the fix is needed within spaCy though - will look into this.

**Comment by nagen01** [comment]
I am getting "The kernel appears to have died. It will restart automatically." while running this same code on my system along with warning message as below:

/home/nb01/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.morphology.Morphology size changed, may indicate binary incompatibility. Expected 104 from C header, got 112 from PyObject
  return f(*args, **kwds)
/home/nb01/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.vocab.Vocab size changed, may indicate binary incompatibility. Expected 96 from C header, got 104 from PyObject
  return f(*args, **kwds)
/home/nb01/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)
