### ISSUE TITLE
attributeerror: type object neuralcoref.neuralcoref.array has no attribute __reduce_cython

### ISSUE THREAD

**Issue by ameyn21** [huggingface/neuralcoref#183]
pyinstaller version: PyInstaller-3.5
OS: Windows10
python version 3.6.7
Cython 0.27.3
spacy 2.1.0. 
NeuralCoref 4.0

I am using pyinstaller to package a working code. I get no errors or warnings when running pyinstaller but when trying to execute the resulting .exe file I get the following error:

**Comment by ameyn21** [comment]
![neuralcoref](https://user-images.githubusercontent.com/8626077/61430939-6133c400-a949-11e9-8ca8-2a7ae2aab7ff.png)

**Comment by ameyn21** [comment]
Hi,
I tried the 'One directory' as well as the "Onefile" packaging but nothing works.

**Comment by svlandeg** [comment]
I'm not sure if this is specific to `neuralcoref`. Have you looked into the potential solutions as described [here](https://stackoverflow.com/questions/51417764/when-using-pyinstaller-got-error-has-no-attribute-reduce-cython)? Either way you may have more luck finding help on StackOverflow for this kind of issue...

**Comment by svlandeg** [comment]
Continuing this discussion [here](https://stackoverflow.com/questions/57175603/has-no-attribute-reduce-cython-error-when-using-pyinstaller-exe/57177165#comment102595427_57177165).

**Comment by binfeng** [comment]
Any fix for this?

**Comment by allanj** [comment]
Got the same issue

**Comment by junglewill** [comment]
Getting the same issue. Does anyone find the solution?
