### ISSUE TITLE
Quote Attribution

### ISSUE THREAD

**Issue by BvdM0** [huggingface/neuralcoref#184]
Is there any way to attribute quotes using neuralcoref, or any compatible code which I could integrate it with to do so?

I switched to neuralcoref from CoreNLP because of its superior coref abilities, but my whole reason for wanting coref is to attribute quotations.

Any help greatly appreciated!

**Comment by julien-c** [comment]
Do you have an example of what you would like to achieve?

**Comment by BvdM0** [comment]
Sure, I'd like to be able to turn text into quotes and attributed speakers [as CoreNLP does](https://stanfordnlp.github.io/CoreNLP/quote.html). For instance:

_In the summer Joe Smith decided to go on vacation.  He said, "I'm going to Hawaii."  That July, vacationer Joe went to Hawaii._

Would return something like this:

```
Extracted quotes: 
[QuotationIndex=0, CharacterOffsetBegin=61, Text="I'm going to Hawaii.", Speaker=Joe Smith]
```

**Comment by AlJohri** [comment]
Linking this issue since quote identification is the first step: https://github.com/explosion/spaCy/issues/4885
