### ISSUE TITLE
Where is the conll parser?

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/neuralcoref#187]
In the [instructions](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md) there is a reference to a conll parser and conll processing scripts, but those links are dead. They have been removed but it's not clear to me why.

**Comment by BramVanroy** [comment]
Bump. Not fixed.

**Comment by svlandeg** [comment]
Hi @BramVanroy , most of the data is moved to https://github.com/huggingface/neuralcoref/tree/master/neuralcoref/train which holds `conllparser.py`. I'm preparing an update of the documentation to reflect these changes. 

The `skeleton2conll.sh` is part of the `conll-2012` download, in the folder `v3\scripts`. If there were ever modified versions of this script, I think that may have indeed be deleted.
