### ISSUE TITLE
transfer learning with small size new domain dataset possible ?

### ISSUE THREAD

**Issue by munaAchyuta** [huggingface/neuralcoref#188]
Hi There,

I am using neuralcoref for my project. great work from you. thanks for sharing.

I am trying to use it for clustering sentences related to entity. and i am trying it for finance domain. and what i see , the default model is trained on news dataset. so when i try to use for finance domain , there are many cases where it failed to identify entity. and as you know there can be project specific entity requirements. 

so thinking is there a way i can use transfer learning for training with new domain ?

Thanks in advance.

**Comment by xiulinyang** [comment]
Hi have you figured it out? I'm interested in similar work, too. :)

**Comment by xiulinyang** [comment]
> Hi have you figured it out? I'm interested in similar work, too. :)
