### ISSUE TITLE
Relative pronouns

### ISSUE THREAD

**Issue by vishalvpv** [huggingface/neuralcoref#19]
Consider the below sentence
50 year old Male with history of alcohol abuse and hypertension who presents with emesis with blood clots.

Is relative pronoun outside the scope of coreference? How do I relate the relative pronoun 'who' to 'Male'?

Best Regards,
Vishal

**Comment by thomwolf** [comment]
Hmm, I think (at least one of) the problem is that it is not a well formed sentence. So the parser can get a good parse tree. (see https://en.wikipedia.org/wiki/Well-formedness for example)
