### ISSUE TITLE
cannot import Coref

### ISSUE THREAD

**Issue by rrrepos** [huggingface/neuralcoref#190]
I am trying to install neuralcoref on jupyter on a mac for testing purposes and getting the following errors:

Spacy version is: 2.1.6

I have installed neuralcoref using `pip install neuralcoref` and ensured that the lib has been downloaded in the correct directory

When I try to use the following command as per the pipeline suggestion in Spacy
`from neuralcoref import Coref` it gives an error: `cannot import name 'Coref' from 'neuralcoref'`

Even if I try: `import en_coref_md` as suggested in an earlier issue it gives: `No module named 'en_coref_md'` 

What am I doing wrong? Thanks

**Comment by rrrepos** [comment]
Instead of using the documentation of spaCy I used the one suggested by neuralcoref and it worked. I should have tried this in the first place. My bad. Here is the code that worked.

```
import neuralcoref
neuralcoref.add_to_pipe(nlp)
```

**Comment by svlandeg** [comment]
Happy to see you got it working! Also, I've fixed the outdated documentation at spaCy's universe to avoid confusion, cf https://github.com/explosion/spaCy/pull/4317.
