### ISSUE TITLE
customising dictionary for identifying proper nouns

### ISSUE THREAD

**Issue by rrrepos** [huggingface/neuralcoref#191]
When using this wonderful library to identify pronouns to names, it works well for popular names like John and Jane. However, it does not recognise many other names (perhaps due to the dictionary having US names). For example: 
```
Given text: John and Jane are neighbours. She admires him because he works hard.

Pronouns and their references:
She => Jane
him => John
he => John
```
But

```
Given text: Ram and Sita are neighbours. She admires him because he works hard.

Pronouns and their references:
him => Ram and Sita
he => Ram and Sita
```

I tried adding
```
add_dict={"Sita": ["woman", "girl"], "Ram": ["man", "boy"]}
coref = neuralcoref.NeuralCoref(nlp.vocab, conv_dict=add_dict)
```
yet
```
Given text: Ram and Sita are neighbours. She admires him because he works hard.

Pronouns and their references:
She => Ram and Sita
him => Ram and Sita
he => Ram and Sita
```

Is there any reason it is not accepting the added words? Thanks

**Comment by munaAchyuta** [comment]
yes, i'm too facing same problem. this is a common issue for new domain . what should be the solution ?
don't see training from beginning with new domain data(small size) is feasible. is there transfer learning possible ?

**Comment by svlandeg** [comment]
Thanks for the report! Merging with Issue #215.
