### ISSUE TITLE
Train the model on chinese OntoNotes 5.0 but eat up all my 64GB memory

### ISSUE THREAD

**Issue by ITonly** [huggingface/neuralcoref#193]
I am training it for Chinese Model to use for event extraction for my company, but I only use part of English data for testing the model, as show in first image(train data ). But it eats up 50% memory(64GB) when build coreference clusters，when I use all data from conll-2012, my memery is 100% and can't run any more. Can you tell me how much memory should I use to train the model, or any other requirements? The attach file is my training machine performance.
![traindata](https://user-images.githubusercontent.com/14368521/62588483-6789e000-b8f8-11e9-81cc-a1c1101a4371.png)
![gpu](https://user-images.githubusercontent.com/14368521/62588664-2e05a480-b8f9-11e9-9d72-49588ac7ce9d.png)
![computer](https://user-images.githubusercontent.com/14368521/62588673-31992b80-b8f9-11e9-871e-47752faea14f.png)

**Comment by svlandeg** [comment]
Hi @ITonly, can you give a bit more detail on which code you were executing exactly, and where you run into memory issues?

Unfortunately I personally don't have experience with retraining this for Chinese.
Have you been able to solve it in the meantime with more RAM?

**Comment by svlandeg** [comment]
Also - this is probably a stab in the dark - but just to make sure: are you running the code from a console directly or from within an IDE? (the latter may be restricting your memory usage)

**Comment by svlandeg** [comment]
One more suggestion: could you try setting `use_gold_mentions=True` (see related Issue #212)

**Comment by Abhijit-2592** [comment]
@ITonly Check my pull request #231. This problem is now resolved. Feel free to get back if you still find memory issues
