### ISSUE TITLE
Ways to fix incorrect coref resolution?

### ISSUE THREAD

**Issue by jeffxtang** [huggingface/neuralcoref#198]
`doc._.coref_clusters`  returned from `doc=nlp('Who ate the cake? Was it the cat?')` is `[the cake: [the cake, it]]`, with the default greedyness value of 0.5. For larger values, the correct reference to "who" still can't be returned.

What're some possible ways to fix this kind of problem? Thanks!

**Comment by svlandeg** [comment]
Thanks for the report! Merging with Issue #215.
