### ISSUE TITLE
Parameterising Coref Resolution

### ISSUE THREAD

**Issue by rrrepos** [huggingface/neuralcoref#199]
Currently, the `doc._.coref_resolved` replaces all cluster objects with the head object. As an enhancement, would it possible to have the replacement only for some tagger properties (e.g. `pos_` or `dep_` or `tag_` so that we can apply our own filters (e.g. pos_ == "PRON"). Something like that. Thanks

**Comment by svlandeg** [comment]
Hi @rrrepos, I think it would make sense that you'd be able to overwrite that default behaviour! Keeping this open as an "enhancement TODO". Feel free to contribute with a PR if you're up to it!
