### ISSUE TITLE
Training/testing workflow

### ISSUE THREAD

**Issue by dmzio** [huggingface/neuralcoref#2]
Thanks for opensourcing this ready to use library! 

In your blogpost you've mentioned initial training on OntoNotes-5. Could you reveal details about performance on that dataset and how current one relates to performance of the original Clark & Manning model?
Do you plan to release code/workflow for retraining/tuning of the model?

**Comment by julien-c** [comment]
Hi @dmzio, @thomwolf can chime in, but yes we are working on releasing the (pyTorch powered) training workflow for this model. 

Subscribe to get updates!

**Comment by bolaft** [comment]
Hello @dmzio and @thomwolf, any update on the training code? The library is really interesting, unfortunately without the ability to train a model it'll remain English-only and many of us can't use that at all. Congrats on the lib though, it's very cool.

**Comment by julien-c** [comment]
Hi @bolaft, quick question – which datasets would you use the training code on? (there are not that many coreference datasets in our experience, so we're super interested of the ones you know about)

**Comment by bolaft** [comment]
Hi @julien-c, I was thinking of the ANCOR corpus [1] for French. It's > 400k words and encodes entities, their properties and anaphoric relations. Do you think it would do the trick?

[1] https://hal.archives-ouvertes.fr/hal-01016562/document

**Comment by tgalery** [comment]
Updates on this would be interesting. It would be nice to maybe document an abstract schema for how the data should look like, so the community can write specific transformation tools to transform corpora from other languages into something that the pipeline can consume effortlessly.

**Comment by julien-c** [comment]
Thanks for the feedback @dmzio @bolaft @tgalery.

We will be releasing the training code + associated documentation next week.

In the meantime, you can follow our progress on the training branch here: https://github.com/huggingface/neuralcoref/commits/training

**Comment by julien-c** [comment]
🎉🎉 Just released v2.0 🎉🎉

Here's a blogpost detailing our work: https://medium.com/huggingface/how-to-train-a-neural-coreference-model-neuralcoref-2-7bb30c1abdfe

We can help anyone who would like to train on a new language.

Feedback appreciated.

**Comment by annkupriyanova** [comment]
How long does it take to train the model (on CPU and on GPU)?

**Comment by julien-c** [comment]
About a day total on GPU

**Comment by thomwolf** [comment]
We are now on release v3.0 so I am closing this old issue.
Feel free to open it again (or a new one) if you are experiencing some issues with the new release.
