### ISSUE TITLE
ImportError: cannot import name 'Coref'

### ISSUE THREAD

**Issue by subhobrata** [huggingface/neuralcoref#201]
Hi,

I am doing following in Google Colab from below spacy site
https://spacy.io/universe/project/neuralcoref

!pip install neuralcoref

from neuralcoref import Coref

coref = Coref()
clusters = coref.one_shot_coref(utterances=u"She loves him.", context=u"My sister has a dog.")
mentions = coref.get_mentions()
utterances = coref.get_utterances()
resolved_utterance_text = coref.get_resolved_utterances()

Getting below error

ImportError                               Traceback (most recent call last)
<ipython-input-3-200cd1cd5eca> in <module>()
----> 1 from neuralcoref import Coref
      2 
      3 coref = Coref()
      4 clusters = coref.one_shot_coref(utterances=u"She loves him.", context=u"My sister has a dog.")
      5 mentions = coref.get_mentions()

ImportError: cannot import name 'Coref'

**Comment by svlandeg** [comment]
Hi @subhobrata , I think that code is outdated. Could you try following neuralcoref's [readme ](https://github.com/huggingface/neuralcoref#loading-neuralcoref) instead:

``` 
import spacy
nlp = spacy.load('en')

import neuralcoref
neuralcoref.add_to_pipe(nlp)

doc = nlp(u'My sister has a dog. She loves him.')

print(doc._.has_coref)
print(doc._.coref_clusters)
```

**Comment by svlandeg** [comment]
See also Issue #91.

**Comment by svlandeg** [comment]
I've also fixed the outdated documentation at spaCy's universe, cf https://github.com/explosion/spaCy/pull/4317.
