### ISSUE TITLE
Runtime Warning and Kernal dies

### ISSUE THREAD

**Issue by raj5287** [huggingface/neuralcoref#202]
HI
I am getting this runtime warning and the kernal dies after that : 

```
/home/user/anaconda3/envs/py37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject return f(*args, **kwds)
```
while running in terminal I can see this : `Segmentation fault (core dumped)` with the above lines
I am usnig spacy 2.1.8 and python 3.7 in jupyter

**Comment by raj5287** [comment]
the issue is with the latest spacy version i.e. 2.1.8. I have tried with spacy 2.1.0 and it is working fine.

**Comment by svlandeg** [comment]
As a workaround for the incompatibility issue, you can indeed either downgrade spaCy to 2.1.0, or [build neuralcoref from source](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source) if you want to use a more recent version of spaCy.

We plan on keeping the releases of neuralcoref and spaCy more in-sync in the future. Merging this with Issue #197.
