### ISSUE TITLE
FileExistsError when making NEURALCOREF_MODEL_PATH

### ISSUE THREAD

**Issue by tuomastik** [huggingface/neuralcoref#204]
I'm getting the following error when running a Docker container that uses gunicorn with multiple workers to serve a Flask app that uses neuralcoref.
```python
  File "/usr/local/lib/python3.7/site-packages/neuralcoref/__init__.py", line 27, in <module>
    os.makedirs(NEURALCOREF_MODEL_PATH)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/root/.neuralcoref_cache/neuralcoref'
```
This StackOverflow post seems to deal with the same issue: [Python “FileExists” error when making directory](https://stackoverflow.com/questions/12468022/python-fileexists-error-when-making-directory)

**Comment by svlandeg** [comment]
Thanks for the report! Do you think this could be fixed by adding `exist_ok=True` to the `mkdirs` call?

**Comment by svlandeg** [comment]
Feel free to submit a PR with the fix!

**Comment by tuomastik** [comment]
Just submitted the PR. I was trying to systematically reproduce the error with a simpler app, but the error happened only every now and then. I guess the error needs perfect timing from all the workers trying to create the directory at the same time.
