### ISSUE TITLE
Unknown morphological feature

### ISSUE THREAD

**Issue by anandhperumal** [huggingface/neuralcoref#206]
Code
```
import spacy
import neuralcoref
neuralcoref.add_to_pipe(nlp)
doc = nlp(u'My sister has a dog. She loves him.')
```

Output:
```
ValueError: [E167] Unknown morphological feature: 'Person' (2313063860588076218). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate
```
en-core-web-sm version 2.2.0

let me know if I'm missing anything

**Comment by anandhperumal** [comment]
It's working as expected.
My code had a bug

**Comment by mmaybeno** [comment]
For context... I had this error as well. My spacy version was different than the model version (2.2.0 & 2.1.0) which caused it to fail. Updating the model fixed it.

**Comment by shelnee** [comment]
Can anyone tell me how to update the model version?

**Comment by mmaybeno** [comment]
Do the normal download of the model you have. For example:
`python -m spacy download en_core_web_sm`

**Comment by skrunt7** [comment]
I am running into the same problem.  I redownloaded the model and am using 2.2.0 but still having an issues.  Spacy is 2.2.1 so I even moved it back to 2.2.0 to see if that was the issue but it still fails when it tries to tag a person.  Is anyone else still seeing this even after redownloading the model?

**Comment by paulmattheww** [comment]
I'm seeing the same thing.  The toy example from SpaCy's website is giving this error
```
ValueError: [E167] Unknown morphological feature: 'Person' (2313063860588076218). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate
```
And the versions are
```
====================== Installed models (spaCy v2.2.2) ======================
ℹ spaCy installation:
/home/jupyter/.local/lib/python2.7/site-packages/spacy

TYPE      NAME             MODEL            VERSION
package   en-core-web-sm   en_core_web_sm   2.2.0   ✔
link      en               en_core_web_sm   2.2.0   ✔
```
