### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by anandhperumal** [huggingface/neuralcoref#207]
when i try to run the following code, the terminal crashes

```
import spacy
import neuralcoref
nlp = spacy.load('en')
neuralcoref.add_to_pipe(nlp)
doc = nlp(u'My sister has a dog. She loves him.')
```

verified it in Colab even in  that session crashes.

**Comment by svlandeg** [comment]
Thanks for the report! What are the versions of `spacy` and `neuralcoref` you're using?

**Comment by npow** [comment]
I ran into this as well. I'm running Python 3.6.6 on OSX.
```
neuralcoref==4.0
spacy==2.2.1
```

**Comment by svlandeg** [comment]
The solution is to either downgrade spaCy, or build neuralcoref from source. Merging with #197

**Comment by jayshow03** [comment]
> 

Thanks so much, that really works for me.

**Comment by jayshow03** [comment]
> > 
> 
> Thanks so much, that really works for me.

Anyone who wants to use neuralcoref on google colab must install spacy 2.1, otherwise, your session will be crashed.
