### ISSUE TITLE
Detection Failing on Longer Sentences

### ISSUE THREAD

**Issue by prakhar21** [huggingface/neuralcoref#21]
Is there any window length over which the model was trained ? It is failing with below given Input. If i reduce some words from between then it works. Looks like it is not handeling longer sentences.

**Input:** "The highest run scorer of all time in International cricket, Tendulkar took up cricket at the age of eleven, made his Test debut on 15 November 1989 against Pakistan. He is the only player to have scored one hundred international centuries.
**Output:**
`
{
                "coreferences": [],
                "mentions": [
                    {
                        "index": 0,
                        "end": 9,
                        "type": "PRONOMINAL",
                        "start": 6,
                        "text": "his",
                        "utterance": 0
                    },
                    {
                        "index": 1,
                        "end": 57,
                        "type": "NOMINAL",
                        "start": 6,
                        "text": "his Test debut on 15 November 1989 against Pakistan",
                        "utterance": 0
                    },
                    {
                        "index": 2,
                        "end": 57,
                        "type": "PROPER",
                        "start": 24,
                        "text": "15 November 1989 against Pakistan",
                        "utterance": 0
                    },
                    {
                        "index": 3,
                        "end": 57,
                        "type": "PROPER",
                        "start": 49,
                        "text": "Pakistan",
                        "utterance": 0
                    },
                    {
                        "index": 4,
                        "end": 61,
                        "type": "PRONOMINAL",
                        "start": 59,
                        "text": "He",
                        "utterance": 0
                    },
                    {
                        "index": 5,
                        "end": 130,
                        "type": "NOMINAL",
                        "start": 65,
                        "text": "the only player to have scored one hundred international centurie",
                        "utterance": 0
                    },
                    {
                        "index": 6,
                        "end": 130,
                        "type": "NOMINAL",
                        "start": 96,
                        "text": "one hundred international centurie",
                        "utterance": 0
                    }
                ],
                "pairScores": {
                    "0": {},
                    "1": {
                        "0": -1.6678770421517723
                    },
                    "2": {
                        "0": -1.8341348680398002,
                        "1": -1.5090962735402649
                    },
                    "3": {
                        "0": -2.6148013630764773,
                        "1": -1.5516474830571154,
                        "2": -1.5169575544555827
                    },
                    "4": {
                        "0": 7.840848417264016,
                        "1": -1.2979947779072352,
                        "2": -1.4595468690699465,
                        "3": -2.0813619591444
                    },
                    "5": {
                        "0": -2.416013286221991,
                        "1": -1.5004609635918187,
                        "2": -1.4986967835407372,
                        "3": -1.8156596791754631,
                        "4": -1.8895537311717003
                    },
                    "6": {
                        "0": -2.5514494172155424,
                        "1": -1.5050492762916694,
                        "2": -1.4961146384932793,
                        "3": -1.5895868435565839,
                        "4": -2.1308741164775555,
                        "5": -1.5027189364339228
                    }
                },
                "singleScores": {
                    "0": null,
                    "1": 1.715603142435672,
                    "2": 1.433124625456641,
                    "3": 1.4715869553088599,
                    "4": -0.6005009606551885,
                    "5": 1.9477583533315648,
                    "6": 1.707929368512381
                }
            }
`

**Expected:** {"He": "tendulkar"}

**Comment by thomwolf** [comment]
Hi @prakhar21,
We have just performed a big update of neuralcoref to version 2.0.
Please install the new version, I have just tested your example and it works and gives a coreference resolved in `The highest run scorer of all time in International cricket, Tendulkar took up cricket at the age of eleven, made tendulkar Test debut on 15 November 1989 against Pakistan. tendulkar is the only player to have scored one hundred international centuries.`
Please reopen the issue or a new issue if you still have some troubles.

**Comment by prakhar21** [comment]
@thomwolf  It works with the updated 2.0
Thanks
