### ISSUE TITLE
Python quit unexpectedly while running scripts

### ISSUE THREAD

**Issue by kameshtj** [huggingface/neuralcoref#210]
First I installed neuralcoref and its dependencies using pip in my global python environment..
When I run the script containing

import spacy
import neuralcoref

nlp = spacy.load('en')
neuralcoref.add_to_pipe(nlp)
doc1 = nlp('My sister has a dog. She loves him.')
print(doc1._.coref_clusters)

doc2 = nlp('Angela lives in Boston. She is quite happy in that city.')
for ent in doc2.ents:
    print(ent._.coref_cluster)

It throws error :
<img width="1003" alt="Screenshot 2019-10-15 at 5 48 25 PM" src="https://user-images.githubusercontent.com/40691729/66830915-2f47f300-ef74-11e9-9c4e-84b6dbd4ae03.png">

Then I tried installing neuralcoref with source, When I run the command 

pip install -e . 

in cloned neuralcoref path, It throws error like below:
<img width="1680" alt="Screenshot 2019-10-15 at 5 43 29 PM" src="https://user-images.githubusercontent.com/40691729/66831090-8f3e9980-ef74-11e9-93ed-777085114990.png">

Kindly anyone help me to resolve this issue
Thanks in Advance.

**Comment by svlandeg** [comment]
When you tried installing from source, did you first run `pip install -r requirements.txt` in a **clean** environment?

**Comment by tylerjthomas9** [comment]
I have a very similar issue when trying to run neuralcoref in google collab. The kernel instantly crashes when creating a doc object with neuralcoref added to the nlp pipeline. 

```
!pip install neuralcoref

# Load your usual SpaCy model (one of SpaCy English models)
import spacy
nlp = spacy.load('en')

# Add neural coref to SpaCy's pipe
import neuralcoref
neuralcoref.add_to_pipe(nlp)

# You're done. You can now use NeuralCoref as you usually manipulate a SpaCy document annotations.
doc = nlp(u'My sister has a dog. She loves him.')

doc._.has_coref
doc._.coref_clusters
```

**Comment by svlandeg** [comment]
What are the versions of spaCy and neuralcoref you're using ?

**Comment by tylerjthomas9** [comment]
spacy = 2.1.8 
neuralcoref =4.0

**Comment by svlandeg** [comment]
Ok so you'd need to either downgrade spaCy to 2.1.0, or keep spaCy as-is but build neuralcoref from source. See also #197

**Comment by kameshtj** [comment]
> Ok so you'd need to either downgrade spaCy to 2.1.0, or keep spaCy as-is but build neuralcoref from source. See also #197

I tried downgrading spacy from spacy==2.2.0 to 2.1.0. This solves the issue. Thanks for your help.
