### ISSUE TITLE
Does not build on newest version of SpaCy, recommend updating requirements.txt

### ISSUE THREAD

**Issue by sidsite** [huggingface/neuralcoref#216]
Hi.

On Ubuntu 18.04.3 LTS, Python 3.6.7, Cython 0.25.

I couldn't get NeuralCoref to build until I downgraded SpaCy from 2.2.1 to 2.1.0. 

Currently requirements.txt has:
spacy>=2.1.0

Recommend adding an upper bound!?

**Comment by svlandeg** [comment]
Thanks for your report, we are aware of the issue, cf. #197.
