### ISSUE TITLE
train conll with BERT

### ISSUE THREAD

**Issue by juliahane** [huggingface/neuralcoref#217]
Hi
I would like to train the conll-2012 data with BERT, for this the common thing is to first convert data to NLI format, then use the NLI bert for it, I was wondering if you could assist and the BERT-based codes to this repo. I really appreciate for your help.
thanks a lot 
Best
Julia

**Comment by svlandeg** [comment]
Hi, this is the repository for coreference resolution, perhaps you meant to post this in https://github.com/huggingface/transformers ?
