### ISSUE TITLE
State-of-the-art benchmark

### ISSUE THREAD

**Issue by Masum06** [huggingface/neuralcoref#218]
Hi,
You are claiming neuralCoref to be state-of-the-art for coreference resolution. Do you have any benchmark supporting the claim? I would like to include it in my paper. Also can it be cited yet?

**Comment by f-lng** [comment]
https://github.com/huggingface/neuralcoref/issues/71

**Comment by svlandeg** [comment]
Also, see https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md#some-details-on-the-training for more details.
