### ISSUE TITLE
Original sentence token position from coref_cluster

### ISSUE THREAD

**Issue by Masum06** [huggingface/neuralcoref#223]
Hi,
`doc._.coref_clusters` returns a list of clusters. But how do I know which element of the cluster refers to which token in the original sentence? Is there a way to get the token position for each coreference?

For example, if one of the elements in `coref_clusters` is _'she'_, I would like to know which _'she'_ is the cluster referring to. Because there can be many _'she'_ in the original sentence.

Thanks in advance.

**Comment by svlandeg** [comment]
`coref_clusters` are coreferring mentions, and these NeuralCoref mentions are spaCy `Span` objects which means you can access all the usual Span attributes. For more information see https://github.com/huggingface/neuralcoref#using-neuralcoref.
