### ISSUE TITLE
Value error when executing program

### ISSUE THREAD

**Issue by feryah** [huggingface/neuralcoref#224]
Hi,
I have this issue when I run the program : 

 neuralcoref.add_to_pipe(nlp)
  File "/Users/name/miniconda3/lib/python3.6/site-packages/neuralcoref/__init__.py", line 37, in add_to_pipe
    nlp.add_pipe(coref, name='neuralcoref')
  File "/Users/name/miniconda3/lib/python3.6/site-packages/spacy/language.py", line 293, in add_pipe
    raise ValueError(Errors.E007.format(name=name, opts=self.pipe_names))
ValueError: [E007] 'neuralcoref' already exists in pipeline. Existing names: ['tagger', 'parser', 'ner', 'neuralcoref']

And I don't get when I run some examples on the command line.

Any help please ?

Thanks a lot!

**Comment by svlandeg** [comment]
The error message points you to the right direction: you already have an `neuralcoref` component in your pipeline `nlp` object. So when you add it again with `add_to_pipe()`, this error is thrown.

I can imagine two cases: either you've called this method twice in your code, or you've loaded an `nlp` object from file which already had the `neuralcoref` in it. Either way - there is no need to add it again, so the line that throws the error, can just be removed from your script.
