### ISSUE TITLE
What is the performance on CoNLL-2012 test set?

### ISSUE THREAD

**Issue by magic282** [huggingface/neuralcoref#227]
Hi,

Thank you for your excellent work. I am looking for an off-the-shelf tool to do some coref text processing. I am wondering about the model performance of this repo on the CoNLL-2012, such as the Avg. F1 score.

Would you please post it here or in the readme file? Thanks a lot.

**Comment by svlandeg** [comment]
Hi, you can find some details & discussion about the performance [here](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md#some-details-on-the-training).

Ofcourse you can also just run the algorithm on any dataset to determine any performance number you'd like ;-)
