### ISSUE TITLE
unable to get few references

### ISSUE THREAD

**Issue by helloworldkr** [huggingface/neuralcoref#229]
Sentence:
"Now keep in mind that Alexander's Force depending on what time we're looking at. It numbers between forty and fifty thousand troops a good number of them infantry  some Cavalry and most of the battles that will see **him** fight, especially the next two against the Persian forces"

resolved output: "Now keep in mind that Alexander's Force depending on what time we're looking at. It numbers between forty and fifty thousand troops a good number of them infantry some Cavalry and most of the battles that will see **Alexander** fight, especially the next two against the Persian forces"

I wanted that  "**It** numbers between" , here the "it" should get replaced by " Alexander's Force"
There is a reference between them as we can observe in the demo website, but I am unable to get it using the example.py in the repository.
![Selection_013](https://user-images.githubusercontent.com/9402190/70376130-b76ec700-192b-11ea-8b78-c4932e6f97a4.png)

**Comment by helloworldkr** [comment]
one more example
for the sentence " Alexander 's really Angry that bestest his killed Darius . He's also likely angry that bestest is claiming that he is the Shan cha and so he kills Rebecca's in Fairly brutal form and there's different accounts of how the killing happened."

response by example.py
 "resolved": "Alexander 's really Angry that bestest his killed Darius . his's also likely angry that bestest is claiming that his is the Shan cha and so his kills Rebecca's in Fairly brutal form and there's different accounts of how the killing happened."

In the case:
"**He's** also likely angry" , here 'he' should get mapped to Alexander but it is getting mapped to his

![Selection_014](https://user-images.githubusercontent.com/9402190/70377918-2a823880-1940-11ea-9fb7-ad732b6c4ff8.png)

**Comment by svlandeg** [comment]
Thanks for the report - merging with Issue #215 !

**Comment by helloworldkr** [comment]
Hi @samhardyhey ,
was just curious to know if the reference is getting created in demo website, then why ain't we getting same result by using example.py (for the above mentioned examples)

**Comment by svlandeg** [comment]
I would assume because the two results are being produced by different models?

**Comment by julien-c** [comment]
Hi @svlandeg and all, the demo website is running a previous release of `neuralcoref` – I should clarify that on the webpage as there are have been a few questions in the past

**Comment by helloworldkr** [comment]
Oh, maybe then I should try the previous version on my project

**Comment by helloworldkr** [comment]
@julien-c can u tell me which version specficially the demo website is running on , so that I can try that out. Thanks
