### ISSUE TITLE
module 'neuralcoref' has no attribute 'add_to_pipe'

### ISSUE THREAD

**Issue by 12102man** [huggingface/neuralcoref#237]
Hey, guys!
I am new to nlp and trying to experiment with your library. I got the following error while trying to run example:
`Traceback (most recent call last):`
  `File "...", line 7, in <module>`
  `  import neuralcoref`
  `File "...", line 8, in <module>`
  `  neuralcoref.add_to_pipe(nlp)`
`AttributeError: module 'neuralcoref' has no attribute 'add_to_pipe'`

My code:
`import spacy`
`text = 'I love apples. They are tasty.'`
`nlp = spacy.load('en')`
`import neuralcoref`
`neuralcoref.add_to_pipe(nlp)`
`doc = nlp(text)`
`print(doc._.coref_clusters)`

What may be wrong here?

**Comment by atestu** [comment]
Make sure that you're using Spacy 2.1.0, neuralcoref is not compatible with the newer Spacy version (unless you build both yourself - see #197)

**Comment by svlandeg** [comment]
Hi @12102man, can you report back after trying these versions?

```
spacy==2.1.3
neuralcoref==4.0.0
```

**Comment by aus10powell** [comment]
The version issue is also an issue for install as I get

`~/opt/anaconda3/envs/mychart-teens-env/lib/python3.7/site-packages/neuralcoref/neuralcoref.cpython-37m-darwin.so in init neuralcoref.neuralcoref()

AttributeError: type object 'neuralcoref.neuralcoref.array' has no attribute '__reduce_cython__'`

error when using `import  #neuralcoref`

**Comment by svlandeg** [comment]
Merging with Issue #197
