### ISSUE TITLE
Domain specific co Coreference

### ISSUE THREAD

**Issue by Prakash100586** [huggingface/neuralcoref#238]
Hi,

I have to solve a domain specific Co reference issue. So my problem is like below.

Example- 
"This crime is committed under Section 120 of IPC and within this section 121 of this act is punishable offence"

Here "121" should refer to the "Section 120 of IPC" 

so 121 and Section 120 IPC are co related. Please can someone suggest me how to train this type of model to solve my problem.

**Comment by svlandeg** [comment]
Hi @Prakash100586, these kind of general usage questions are probably better asked at Stackoverflow, where you are likely to get more response from other people who are trying to do the same. We try to keep this issue tracker focused on bugs and feature requests as we don't have the resources to help with specific use-cases.

That having said, you'll probably want to annotate some data for your specific problem domain. Good first pointers would be [Thomas' blog post](https://medium.com/huggingface/how-to-train-a-neural-coreference-model-neuralcoref-2-7bb30c1abdfe), and our [readme section](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md) on training your own model.
