### ISSUE TITLE
Train on a new language static/tuned embeddings

### ISSUE THREAD

**Issue by zoodyy** [huggingface/neuralcoref#245]
Hi,
thank you for your great software and initial instructions [for training on a new language](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md#train-on-a-new-language). I am currently stuck at the step "Find a set of pre-trained word vectors in your language". The unmodified training scripts require the files in the weights directory, they load static/tuned English embeddings. Could you elaborate how these files can  be replaced with other embeddings (e.g. fasttext)? How are the tuned embeddings produced?
Are the other weight files also required for training (and also English specific)?
Many thanks in advance!

**Comment by EricLe-dev** [comment]
Good question,

I would like to know also. The instruction now is quite vague to me especially the static/tuned embeddings. I'm training the neuralcoref on a new language (Dutch) using the SoNar dataset. I only have the Dutch static word embedding and have no idea what the tuned embeddings is. Would be nice if you guys can share some info or a quick tip about these.

Many thanks in advance!
