### ISSUE TITLE
Splitting large documents into smaller chunks

### ISSUE THREAD

**Issue by Hazoom** [huggingface/neuralcoref#247]
When trying to parse a large document (hundreds of paragraphs) the model is crashing due to lack of memory.
In addition, I don't think that is logically correct to parse huge documents because the model was trained on document of an average of ~2.5KB of text and it can lead to poor performance.

I'd like to know if you have any recommendation how to split the document to chunks such that the model will yield less errors. Of course that one can split it by a hard limit of 2.5KB (without breaking paragraphs, if possible), but this is a naive approach that can lead to potential errors on cases where there are mentions with antecedents on previous chunks.

I was thinking to running the model with a rolling window and look on the places where there is a minimum number of connection breaking between mentions to their antecedents and use those points as splitting points.

**Comment by svlandeg** [comment]
There's not really a universally correct answer to this question, but I think that your suggested approach would make sense. 

The other idea that comes to mind is to check whether new Named Entities are being introduced or not. For instance, One long text may talk about the same guy "Adam", all the time referring back to him with "he" etc. But if 5 other `Person` Named entities are introduced in a new paragraph, the author will need to restate "Adam" if he wants to refer back to him without ambiguity. So this may be another clue to look for when trying to heuristically split up your documents into paragraphs.

**Comment by Hazoom** [comment]
Thank you @svlandeg
