### ISSUE TITLE
German Training not working

### ISSUE THREAD

**Issue by SimonF89** [huggingface/neuralcoref#248]
Hi we tried to train your model for german. We used Glove in german but it doesnt work.

How does the binary static_word_embeddings.npy needs to be structured?

**Comment by boehm-e** [comment]
Would like to know too :)

**Comment by SergejSchweizer** [comment]
This would be nice.

**Comment by EricLe-dev** [comment]
After digging deeper for a while, I found out that the static_word_embeddings.npy is just a numpy list of vectors. You need also a static_word_vocab.txt with corresponding words to the vectors saved in static_word_embeddings.npy. 

However, I have no clue why the tuned_word_embeddings is needed, and how to create it. I checked the original tuned_word_embeddings, it has the words that already included in the static_word_embedding, but also words that are not. The size of the file is much smaller. 

In addition, they have special tokens like <missing> and <*UNK*> (still in doubt what they defined as a "missing token" and an "unknown token"). @svlandeg I have you have answer for those questions. Thank you so much!

**Comment by snape6666** [comment]
any news? has anyone managed to train it?
