### ISSUE TITLE
RuntimeWarning: * size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by fhamborg** [huggingface/neuralcoref#249]
This is related to https://github.com/huggingface/neuralcoref/issues/197 and occurs when using spacy 2.2 and neuralcoref. Installation finished successfully.

I think the readme.md requires some improvement. You already mention explicitly one issue, i.e., the `spacy.strings.StringStore size changed` error, and describe one way to address that issue. However, even when installing with the `--no-binary` people will run into the attached errors, definitely when using spacy 2.2. So, I suggest that you either list the workaround for those, too, or remove the current workaround and only point to issue #197 since the workaround that is currently provided does not get the job done.

```
(ctsacuda) ➜  ctsacuda python
Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:03:29)
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> import neuralcoref
/Users/felix/anaconda3/envs/ctsacuda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.morphology.Morphology size changed, may indicate binary incompatibility. Expected 104 from C header, got 112 from PyObject
  return f(*args, **kwds)
/Users/felix/anaconda3/envs/ctsacuda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.vocab.Vocab size changed, may indicate binary incompatibility. Expected 96 from C header, got 104 from PyObject
  return f(*args, **kwds)
/Users/felix/anaconda3/envs/ctsacuda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)
```

**Comment by virorum** [comment]
Sure would be nice to get this working with spaCy 2.2+

**Comment by svlandeg** [comment]
@fhamborg : you're right, it would be good to update the readme. Feel free to submit a PR!

@virorum : as described in more detail in Issue #197, it does work with spaCy > 2.2 if you compile from source
