### ISSUE TITLE
How can I get the offset position of each mention returned by coref.get_mentions()

### ISSUE THREAD

**Issue by smudgekick** [huggingface/neuralcoref#25]
Currently 'coref.get_mentions()' only returns a list mentions.  Ideally, it would be helpful to get a list of dictionaries returned with the mention and its offset position within the utterance (basically the string being passed in for processing).

Is there a way do this?

**Comment by thomwolf** [comment]
Hi Bryan, the `Mention` class of neuralcoref is a subclass of spaCy `Span` class so you can access all the attributes of a spaCy span in the mention like offset position, length, etc.
For example: `coref.get_mentions()[0].start` will gives you the token offset for the start of the first mention.
Check spaCy Span API doc for the full list and more information: https://spacy.io/api/span#attributes
