### ISSUE TITLE
Hello error while trying to install with :pip install neuralcoref --no-binary neuralcoref

### ISSUE THREAD

**Issue by stin911** [huggingface/neuralcoref#252]
this is the error that I get when I try to run the installation from command line :
os versio: catalina 10.15.4

:/private/var/folders/fx/k8zb04513zx8klcj_8yj9hzw0000gn/T/pip-install-99rhdh6c/neuralcoref/include/numpy/npy_deprecated_api.h:11:2: warning: "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
     ^
    neuralcoref/neuralcoref.cpp:610:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fx/k8zb04513zx8klcj_8yj9hzw0000gn/T/pip-install-99rhdh6c/neuralcoref/setup.py'"'"'; __file__='"'"'/private/var/folders/fx/k8zb04513zx8klcj_8yj9hzw0000gn/T/pip-install-99rhdh6c/neuralcoref/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/fx/k8zb04513zx8klcj_8yj9hzw0000gn/T/pip-record-8jyzqrub/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/neuralcoref Check the logs for full command output.

**Comment by aidenchia** [comment]
same problem, same iOS version

**Comment by griff4692** [comment]
x3.  Does anyone have a workaround?  If I install through pip (even with `--no-binary neuralcoref` arg), I get the error described in the README.

**Comment by scorp-13** [comment]
Facing a similar issue! Any workaround yet?

**Comment by ym-han** [comment]
I had a similar (but I think not exactly the same) issue. What helped me was:
1. making sure to do a `pip uninstall neuralcoref` first
2. Then installing neuralcoref from source, per the instructions in the readme (I used a conda environment and that worked fine)

**Comment by MahadShbeeb** [comment]
same issue with pycharm although it worked in anaconda

**Comment by scorp-13** [comment]
I got this working after downgrading SpaCy version to 2.1.0. 
I am using conda as well, installing from source didn't help me, the requirements.txt file says required version of Spacy to be between 2.1.0 and 2.1.9, I had 2.1.9 installed; still neuralcoref library installation resulted in the above error!

**Comment by MulinT-UN** [comment]
same issue... downgrading SpaCy version to 2.1.0 didn't work for me. Any other fixs?

**Comment by aus10powell** [comment]
I had same problem. Seems definitely to be tied to OS. For my current machine Catalina 10.14, i can't recall exactly, but I believe it was spacy 2.1.4 that worked

**Comment by svlandeg** [comment]
Merging this issue with https://github.com/huggingface/neuralcoref/issues/197 - see there for more pointers on installation!
