### ISSUE TITLE
"Segmentation fault" Error while using sentencizer

### ISSUE THREAD

**Issue by tuner007** [huggingface/neuralcoref#253]
Below code gives segmentation fault error and script closes instantly.
I know it is related to my cloudera environment. But can someone help me understand the reason behind it ?
It works fine on my local windows environment.
```
import neuralcoref
from spacy.lang.en import English
greedyness: float=0.45
language = English
nlp = language()
nlp.add_pipe(nlp.create_pipe('sentencizer'))
neuralcoref.add_to_pipe(nlp, greedyness=greedyness)
doc = nlp("myname is tuner")._.coref_resolved
```

**Comment by svlandeg** [comment]
Are you still running into this? Could you paste the full error?

Could it be due to some binary incompatibilities? Can you start installing from scratch in a clean environment?

**Comment by svlandeg** [comment]
Closing this as there was no reply to the request for further information. Hope it got solved in the meantime! If not, feel free to respond and we can reopen, or start a new issue.
