### ISSUE TITLE
Can't locate CorScorer.pm

### ISSUE THREAD

**Issue by EricLe-dev** [huggingface/neuralcoref#256]
Dear guys,

Thank you for your interesting works. I'm training the model for new language (Dutch) using the SoNars corpus. Due to the fact that SoNars was in MMAX, I used the modification of this script (https://github.com/andreasvc/dutchcoref/blob/master/mmaxconll.py) to convert it to CONLL format.

After that, I trained a word2vec model (to prepare the static_word_embeddings files), I still have no clue what tuned_word_embeddings are, but I just use exactly the same static_word_embeddings files and it seemed to worked. I modified the load_function and other related functions as stated in the tutorial for training new language. Everything went well until the training, I got this error:

`Error during the scoring
Command '['perl', 'c:\\users\\administrator\\desktop\\neural_coref\\neuralcoref\\neuralcoref\\train\\scorer_wrapper.pl', 'muc', 'c:\\users\\administrator\\desktop\\neural_coref\\neuralcoref\\neuralcoref\\train/data//key.txt', 'c:\\users\\administrator\\desktop\\neural_coref\\neuralcoref\\neuralcoref\\train\\test_mentions.txt']' returned non-zero exit status 2.
Can't locate CorScorer.pm in @INC (you may need to install the CorScorer module) (@INC contains: scorer/lib /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at c:\users\administrator\desktop\neural_coref\neuralcoref\neuralcoref\train\scorer_wrapper.pl line 16.
BEGIN failed--compilation aborted at c:\users\administrator\desktop\neural_coref\neuralcoref\neuralcoref\train\scorer_wrapper.pl line 16.`

I could not find any information about the CorScorer.pm on anywhere on the internet. Can someone please help me to fix this? Am I doing anything wrong?

**Comment by svlandeg** [comment]
Hi @EricLe-dev, if you found a solution to your problem, could you please post it? This may help others who come here after googling a similar problem.

**Comment by Schuldts** [comment]
Hi @EricLe-dev! 
We encountered the same error message. For us, the CorScorer.pm file was not present in our repo, it seems like the .gitignore excluded it for some reason. 
Make sure that the `lib` directory is included in the `neuralcoref/train/scorer directory`, as can be seen hear:
https://github.com/huggingface/neuralcoref/tree/master/neuralcoref/train/scorer.

Hope it helps!
Emma, Caroline and Moa
