### ISSUE TITLE
Coref.get_most_representative fails on type error

### ISSUE THREAD

**Issue by sbutner** [huggingface/neuralcoref#26]
Running the server per readme, get an error when trying the sample curl. 
Running `python algorithm.py` to trigger `__main__` produces the following output.

```
[I, many friends, around me, me, many friends, around me received it, it, It, almost everyone, almost everyone received this SMS, this SMS]
[Yes, I noticed that many friends, around me received it. It seems that almost everyone received this SMS.]
['Yes, I noticed that many friends, around me received it. It seems that almost everyone received this SMS.']
```
The error when called from server is 
```
algorithm.py line 347 
coreferences[self.data.mentions[key]] = mention
raises TypeError: unhashable type: 'Mention'
```
Mention class is defined in document.py. It inherits from spacy.tokens.Span but does not implement __hash__().

**Comment by sbutner** [comment]
falcon: 1.4.1
spacy: 1.8.1
numpy: 1.14.2
python: 3.5.2

**Comment by thomwolf** [comment]
We are now on release v3.0 so I am closing this old issue.
Feel free to open it again (or a new one) if you are experiencing some issues with the new release.
