### ISSUE TITLE
Failure to install in Pycharm IDE

### ISSUE THREAD

**Issue by SanJacintoJoe** [huggingface/neuralcoref#266]
When I try to install the package with pip, the installation fails. 
I'm currently running python 3.8 and spacy version 2.3 in Pycharm IDE.

`running build_ext
    building 'neuralcoref.neuralcoref' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: `

I'm not sure what I should do here? Is neuralcorf not compatible with Pycharm?

Thanks in advance.

**Comment by XWilliamY** [comment]
I got this error while installing spaCy. As the error suggests, it seems like you're missing Microsoft C++ Build Tools. You can install the package here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Ramakirishnan** [comment]
> I got this error while installing spaCy. As the error suggests, it seems like you're missing Microsoft C++ Build Tools. You can install the package here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

Have got the same error. I have installed the Build Tools. Still have the same error.

**Comment by svlandeg** [comment]
@Ramakirishnan : There is not a neuralcoref version compatible with spaCy 3.0.3 yet - but it's on the roadmap. cf https://github.com/huggingface/neuralcoref/issues/295

@SanJacintoJoe : You'll find some additional information in https://github.com/huggingface/neuralcoref/issues/197
