### ISSUE TITLE
Loading New model

### ISSUE THREAD

**Issue by firasfrikha** [huggingface/neuralcoref#271]
hello everyone,
have any one succeded to load a new model,
I have some question and i hope if somebody could help me plz

**Comment by svlandeg** [comment]
Hi @firasfrikha, unfortunately the way a Github tracker is set up, makes it unsuitable for lengthy "forum-like" discussions. If you run into specific issues, it's always good to provide a minimal code snippet that produces the error, so people can try and reproduce and understand what may be the problem.

**Comment by svlandeg** [comment]
I'll close this generic question for now - but feel free to open a new, more focused issue as described, if need be.
