### ISSUE TITLE
RuntimeWarning when use  spacy==2.3.2 

### ISSUE THREAD

**Issue by wwpstl** [huggingface/neuralcoref#279]
i got this error 
==================================
RuntimeWarning: spacy.morphology.Morphology size changed, may indicate binary incompatibility. Expected 104 from C header, got 112 from PyObject
  return f(*args, **kwds)

RuntimeWarning: spacy.vocab.Vocab size changed, may indicate binary incompatibility. Expected 96 from C header, got 112 from PyObject
  return f(*args, **kwds)

RuntimeWarning: spacy.tokens.span.Span size changed, may indicate binary incompatibility. Expected 72 from C header, got 80 from PyObject
  return f(*args, **kwds)

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

==============================================

OS is mojave 10.14.1
 Version Python 3.7.6

**Comment by binarymax** [comment]
I also got this error.  Looking at the requirements.txt file I see ```spacy>=2.1.0,<2.2.0``` ...so I'll downgrade spacy to 2.1.x and hopefully that solves the issue, but someone with more knowledge of the library might want to upgrade to work with newer versions of spacy (I'm just toying around now)

**Comment by binarymax** [comment]
Confirmed that downgrading spacy to 2.1.0 fixed the problem.  It is likely a change in spacy 2.3 that introduced the incompatibility.

**Comment by wwpstl** [comment]
> I also got this error. Looking at the requirements.txt file I see `spacy>=2.1.0,<2.2.0` ...so I'll downgrade spacy to 2.1.x and hopefully that solves the issue, but someone with more knowledge of the library might want to upgrade to work with newer versions of spacy (I'm just toying around now)

thanks. it is very embarrassed that i want use `zh_core_web_sm` model ,but  the spacy2.1 do not  support.

**Comment by svlandeg** [comment]
Could you try building your required version of spaCy [from source](https://github.com/explosion/spaCy#compile-from-source), and then [build neuralcoref from source](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source) as well?

**Comment by wwpstl** [comment]
> Could you try building your required version of spaCy [from source](https://github.com/explosion/spaCy#compile-from-source), and then [build neuralcoref from source](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source) as well?

thanks very much. I only  [build neuralcoref from source](https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source) Solved the problem.  Hope it helps someone.

**Comment by svlandeg** [comment]
Happy to hear it! For future reference, there are more details on this issue provided here: https://github.com/huggingface/neuralcoref/issues/197
