### ISSUE TITLE
Release version number still stay at 0.1 for 2.0

### ISSUE THREAD

**Issue by kfkelvinng** [huggingface/neuralcoref#28]
https://github.com/huggingface/neuralcoref/blob/2.0/setup.py#L4

Also 2.0 tag seems to be quite different and unstable. Going to post some diff

**Comment by thomwolf** [comment]
Hi kevin, thanks for that, I will update (a new version is coming soon actually, with huge speed up).
Do you have more information on what you mean by "unstable"?

**Comment by kfkelvinng** [comment]
Taking the example text from Winograd Challenge `When they had eventually calmed down a bit, and had gotten home, Mr. Farley put the magic pebble in an iron safe. Some day they might want to use it, but really for now, what more could they wish for?`

SpaCy 2.0 may have broken the mention detection for `magic pebble`

```
[they,
 a bit,
 Mr. Farley,
 Farley,
 the magic,
 an iron safe,
 safe,
 Some day,
 they,
 it,
 really for now, what more,
 what more,
 they]
```

`spacy==1.8.2` and `en_core_web_sm-1.2.0`
`[they, a bit, Mr. Farley, Farley, the magic pebble, an iron, Some day, they, it, really for now, they]`

**Comment by thomwolf** [comment]
We are now on release v3.0 so I am closing this old issue.
Feel free to open it again (or a new one) if you are experiencing some issues with the new release.
