### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\.neuralcoref_cache\\neuralcoref\\single_model

### ISSUE THREAD

**Issue by kunalkharsadia** [huggingface/neuralcoref#281]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Anaconda3_2020\lib\site-packages\neuralcoref\__init__.py in add_to_pipe(nlp, **kwargs)
     34 
     35 def add_to_pipe(nlp, **kwargs):
---> 36     coref = NeuralCoref(nlp.vocab, **kwargs)
     37     nlp.add_pipe(coref, name='neuralcoref')
     38     return nlp

neuralcoref.pyx in neuralcoref.neuralcoref.NeuralCoref.__init__()

neuralcoref.pyx in neuralcoref.neuralcoref.NeuralCoref.from_disk()

~\Anaconda3_2020\lib\pathlib.py in open(self, mode, buffering, encoding, errors, newline)
   1201             self._raise_closed()
   1202         return io.open(self, mode, buffering, encoding, errors, newline,
-> 1203                        opener=self._opener)
   1204 
   1205     def read_bytes(self):

~\Anaconda3_2020\lib\pathlib.py in _opener(self, name, flags, mode)
   1056     def _opener(self, name, flags, mode=0o666):
   1057         # A stub for the opener argument to built-in open()
-> 1058         return self._accessor.open(self, flags, mode)
   1059 
   1060     def _raw_open(self, flags, mode=0o777):

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\.neuralcoref_cache\\neuralcoref\\single_model'

**Comment by kunalkharsadia** [comment]
please help. Error occurs while trying to run the neuralcoref 4.

**Comment by svlandeg** [comment]
Can you provide some more background, which code are you trying to execute? How did you install `neuralcoref`?

**Comment by kunalkharsadia** [comment]
It occurs in nueralcoref.add_to_pipe(nlp). apparently turns out that there was no single model file in my .neuralcoref_cache. 

I faced this issue while replicating a code which was already working on one workstation to another. i have fixed this by sharing the .neuralcoref_cache folder from the workstation where it works to the workstation where it doesn't.

**Comment by kunalkharsadia** [comment]
although i would like you to get to the bottom of this. A similar issue was open and i could not find any solution hence i had to ask the question.

**Comment by svlandeg** [comment]
This type of issue is usually a problem with a local installation, as seems to be the case here as well. Unless you provide us with a path to try and replicate the issue, there's not much we can do. As this seems to be solved now on your end, I'll go ahead and close this. Thanks for reporting back!
