### ISSUE TITLE
Unknown morphological feature: 'Person' 

### ISSUE THREAD

**Issue by viva2202** [huggingface/neuralcoref#284]
Hey I'm using 

====================== Installed models (spaCy v2.2.0) ======================
ℹ spaCy installation:
C:\Users\Admin-vviellieber\.conda\envs\untitled\lib\site-packages\spacy

TYPE      NAME             MODEL            VERSION
package   en-core-web-sm   en_core_web_sm   2.2.0     ✔

and when 

```
import en_core_web_sm
nlp = en_core_web_sm.load()

example_doc = nlp("There is a break in connectivity frequently with the audio on Bluetooth.")
```

and many other input sentences I receive this error:

ValueError: [E167] Unknown morphological feature: 'Person' (2313063860588076218). This can happen if the tagger was trained with a different set of morphological features. If you're using a pretrained model, make sure that your models are up to date:
python -m spacy validate

and there is en_core_web_sm version the same as spaCy is. 

When I use some other sentences like 

`doc = nlp("The customer service was terrible.")`

it is working. 

Can someone help me to solve this?

**Comment by svlandeg** [comment]
Can you provide the output of running these commands?
```
python -m spacy validate
python -m spacy info --markdown
```
