### ISSUE TITLE
about stage swich condition

### ISSUE THREAD

**Issue by hitxujian** [huggingface/neuralcoref#29]
hi：
after seeing the code, the stage switch is controlled by  learning rate decrease,which is not controlled by metrics on the dev set. is this true?

  lr = decrease_lr(optim_func)
  if args.on_eval_decrease == 'next_stage' or lr <= args.min_lr:
            print("Switch to next stage")

**Comment by thomwolf** [comment]
Hi @hitxujian,
I don't think so, it should controlled by the evaluation metric. I think the metric evaluation is just before the part you copied, see [line 222](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/learn.py#L222)

By the way, one argument (`--on_eval_decrease`) is a switch to select between three behaviors when the evaluation metric stagnate:
- `nothing` => does nothing,
- `divide_lr`=> reduce the learning rate
- `next_stage` => switch to the next stage
- `divide_then_next` => reduce the learning rate until we reach `--min_lr` then switch to the next stage
