### ISSUE TITLE
Not able to generate coreferencing for a series of statements more than 500 words

### ISSUE THREAD

**Issue by shivakarthiks** [huggingface/neuralcoref#3]
@julien-c 
I have tried using your system for co-referencing. It was giving promising results till 500 words, but it is not able to do co-referencing above 500 words. I have tried both in online as well as hosted version. Can you please update the same for above 500 words too?

**Comment by julien-c** [comment]
Yes, there is currently a hardcoded limit on the number of tokens. You have to tweak the code if you want to increase it (cc @thomwolf)

**Comment by fraizier-reiland** [comment]
@shivakarthiks , if you go into algorithm.py and look at the arguments for the __init__ method for the Coref class you can see the hardcoded limit (i.e. max_dist_match=500). 

You could try to increase this number to satisfy your needs but I am not sure of the implication of making that change.

**Comment by thomwolf** [comment]
We are now on release v3.0 so I am closing this old issue.
Feel free to open it again (or a new one) if you are experiencing some issues with the new release.
