### ISSUE TITLE
result not matched as demo

### ISSUE THREAD

**Issue by khliu1238** [huggingface/neuralcoref#30]
considering this sentence:

According to this legend, Captain James Cook and naturalist Sir Joseph Banks were exploring Australia when they happened upon the animal. They asked a nearby local what the creatures were called.

In which 'they' in the second sentence should be resolved as 'Captain James Cook and naturalist Sir Joseph Banks'. On demo site this is roughly right, but from the output of the latest code this is not the case:

```
coref.one_shot_coref(utterances=u"According to this legend, Captain James Cook and naturalist Sir Joseph Banks were exploring Australia when they happened upon the animal. They asked a nearby local what the creatures were called.", context=u"")
resolved_utterance_text = coref.get_resolved_utterances()
print(resolved_utterance_text)
``` 
['According to this legend, Captain James Cook and naturalist Sir Joseph Banks were exploring Australia when they happened upon the animal. They asked a nearby local what the creatures were called.']

why is that?

**Comment by thomwolf** [comment]
Humm I suspect it is a matter of quality of parsing, our demo used a spacy 1 model with a rather high parsing accuracy. I will investigate that.

**Comment by thomwolf** [comment]
Further investigations confirmed that it is indeed an issue with the accuracy of the spacy model you use like #16.
Here also the most simple solution is to use the larger model [en_core_web_lg](https://spacy.io/models/en#en_core_web_lg) which label this example correctly.

Currently spacy model is hard coded to `en_core_web_sm`, you can overcome it by passing an nlp object to coref constructor. In the next version I will release in a few days I will make it easier to use any spacy model.

**Comment by thomwolf** [comment]
We are now on release v3.0 so I am closing this old issue.
Feel free to open it again (or a new one) if you are experiencing some issues with the new release.
