### ISSUE TITLE
Out of Vocabulary Words

### ISSUE THREAD

**Issue by jh0274** [huggingface/neuralcoref#31]
Hi
Firstly, what you've done looks great - thank you. Secondly I'm interested in a feature that you hint at in your 1st blog post:
 _2.We make use of recent work on word embeddings to compute embeddings for unknown words on the fly from definitions or information that you can provide (it’s very simple in fact: you can compute a word embedding for “Kendall Jenner” simply by averaging the vectors for “woman” and “model” for example)._
I'd like to know how to supplement the definitions/information you refer to above. I'm working within a domain that has some very specific/unique terms that will not be in the training corpus and I'd like to know how to use/supplement the code to embed vectors in the way you describe above,
Thanks

**Comment by thomwolf** [comment]
Hi @jh0274,
Indeed, it is not included in the currently open-sourced version of neuralcoref.
I will see if I can add it to the next release.

**Comment by jh0274** [comment]
Thanks a lot!

**Comment by thomwolf** [comment]
Couldn't easily integrate this features in the new release which is tightly integrated with spaCy pipeline but I hope we cant get it in for the next release. Will keep you tuned.

**Comment by thomwolf** [comment]
Hi this has been added in the latest release (4.0).
