### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by 99sbr** [huggingface/neuralcoref#32]
Getting this error when running learn.py to train on GPU server-
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.cuda.IntTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)
On line "embed_words = self.drop(self.word_embeds(words).view(words.size()[0], -1))"
line 72 of model.py

**Comment by thomwolf** [comment]
Hi @99sbr, which version of PyTorch and configuration are you using?

**Comment by 99sbr** [comment]
@thomwolf  pytorch v0.3
