### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by negacy** [huggingface/neuralcoref#34]
Which of the columns in the CoNLL format are required to train the system on a new dataset? Here is an example of a sentence that I have from my dataset, can someone comment please if this is an acceptable format:
![image](https://user-images.githubusercontent.com/4706017/40022711-03a507ec-5786-11e8-9168-7739a89bcda5.png)

However, with this dataset, I am having the following error message, any help please?

Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/neha5486/git/neuralcoref/neuralcoref/conllparser.py", line 714, in <module>
(my-vitual-env) -bash-4.2$
  File "/Users/neha5486/git/neuralcoref/neuralcoref/conllparser.py", line 649, in build_and_gather_multiple_arrays

ict[feature]))
TypeError: object of type 'NoneType' has no len()

**Comment by thomwolf** [comment]
Hi @negacy,
I show an example of file in the blog post detailing the training process [here](https://medium.com/huggingface/how-to-train-a-neural-coreference-model-neuralcoref-2-7bb30c1abdfe).
The main function parsing the file is `load_file` in `collparser.py which is [here](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/conllparser.py#L119)
You should check it to see the file format and adapt it if you don't use the OntoNote dataset.

**Comment by negacy** [comment]
Hi @thomwolf, 
I prepared my dataset similar to the CoNLL format, but since some of the information are missing, for example column number 6, I was wondering if all the columns are required in order to continue training. Thanks. Negacy.
