### ISSUE TITLE
Getting cluster ids per word in original text

### ISSUE THREAD

**Issue by theSage21** [huggingface/neuralcoref#37]
First, Thank you for the work :+1: It has made life a lot easier.

In the usage of `coref.get_resolved_utterances()`, I was wondering if there is some way of generating a mapping saying that each word in the original text belongs to which cluster(s). Maybe like:

John | used |  to | work |  for | the |  army | . | He| was | an | epitome | of | discipline
----|----|----|----|----|----|----|----|----|----|----|----|----|--
0 |  |  |  |  | 1 | 1 |  | 0 |  |  |  |  |

I've tried to do this with get_clusters and get_mentions but the problem is that mentions are not unique in the original text.

Is there something I'm missing or should I fork and dive into neuralcoref code?

**Comment by thomwolf** [comment]
Hi Arjoonn,
Yeah, it will be a lot easier (and faster) in the new version that is coming next week or so, but for now I think something like the following should work (haven't tried it):
````
text = u"John used to work in the army"
clusters = coref.one_shot_coref(text)
doc = coref.data.utterances[-1]
mapping = [None]*len(doc)
for cluster_idx, mentions in clusters.items():
    for mention_idx in mentions:
        for token in coref.data.mentions[mention_idx]:
             mapping[token.i] = cluster_idx
````

**Comment by theSage21** [comment]
This worked with a little tweaking `clusters, _ = coref.one_shot_coref(text)`. Thanks.
