### ISSUE TITLE
Improvising time for coreferencing

### ISSUE THREAD

**Issue by bharath45** [huggingface/neuralcoref#4]
Hi julien, thanks for opensoursing such an amazing library for coreferencing

I have two questions 
  -Have you released pyTorch powered training workflow yet. If yes can you please provide a link for the same.
 - Now with this current flow, coreferencing a 10kb file takes 30 seconds on my machine. Will the time for coreferncing come down drastically using a GPU.?

**Comment by julien-c** [comment]
Hi @Nbharath all the credit goes to @thomwolf 👏 

We haven't published the training workflow yet but it is coming in couple of weeks.

**Comment by julien-c** [comment]
As for the resolution time, I'll let Thomas pitch in!

**Comment by thomwolf** [comment]
Hi @Nbharath,
- I am currently cleaning up the pyTorch code and taking the occasion to refine a bit the mention detection algorithm. I will publish the code as soon as possible.
- Right now the library uses numpy to compute the matrix multiplication so it can't make use of the GPU. To put it on GPU we would also have to refactor a bit the workflow to parallelize the computation of pair scores. We use it for very small files (dialog) so it is not in my top priority list but if you feel like trying, you are more than welcome ! (maybe using something like [cupy](https://github.com/cupy/cupy) would be the simplest way)

**Comment by lavinadurgani** [comment]
Hello Thomas, 

Is the pyTorch code published now ? Will the pyTorch code help to reduce the coreference resolution processing speed if executed on GPU

Regards,
Lavina

**Comment by arunzz** [comment]
Hello

First of all, thanks for the nice library.
The time taken is very long for an average size content. The number of mentions detected are more and we cut short some of the accepted entities and some grammar rules but still the time is too long.
Any tips on how can we reduce it? Please let know.

**Comment by thomwolf** [comment]
Yes, just wait for the release of version 0.3 (hopefully) next week.
Version 0.3 will be about 20 times faster :-)

**Comment by arunzz** [comment]
Glad to know. I will keep waiting then. :)

**Comment by dlindbe** [comment]
Is there a new ETA for the cython rewrite?

**Comment by thomwolf** [comment]
Yes, it should be this week, the code pretty much ready (see extension branch), I just have to finish a few edge cases and functions and write the doc (it's now integrated as a spaCy extension so the interface is a bit different). It'll be 50 to 100 times faster on a large doc.

**Comment by theSage21** [comment]
any way we can help out?

**Comment by pramod2157** [comment]
@thomwolf  when the Cython version will be released?

**Comment by thomwolf** [comment]
It is released! I have updated the readme!

**Comment by pramod2157** [comment]
Just tried running it on multiple instances, it works amazing. Thanks @thomwolf

**Comment by arunzz** [comment]
It gives an error while loading the new model saying unicode expected not char in line import neuralcoref.

Can you pls help
