### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Skulsta** [huggingface/neuralcoref#43]
I'm not able to install it. Any suggestion is much appreciated.

$ pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_lg-3.0.0/en_coref_lg-3.0.0.tar.gz
Collecting https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_lg-3.0.0/en_coref_lg-3.0.0.tar.gz
  Downloading https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_lg-3.0.0/en_coref_lg-3.0.0.tar.gz (892.8MB)
    100% |████████████████████████████████| 892.8MB 27kB/s
    Complete output from command python setup.py egg_info:
    (u'model_name', 'en_coref_lg')
    (u'model_dir', u'en_coref_lg/en_coref_lg-3.0.0')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vk/f4v089pd43jf98dcbzfwjnnr0000gn/T/pip-req-build-3XD223/setup.py", line 98, in <module>
        setup_package()
      File "/private/var/folders/vk/f4v089pd43jf98dcbzfwjnnr0000gn/T/pip-req-build-3XD223/setup.py", line 75, in setup_package
        extra_link_args=extra_link_args))
      File "/Users/stian/projects/figaro-tagger/venv/lib/python2.7/site-packages/setuptools/extension.py", line 39, in __init__
        _Extension.__init__(self, name, sources, *args, **kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/extension.py", line 106, in __init__
        assert type(name) is StringType, "'name' must be a string"
    AssertionError: 'name' must be a string

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vk/f4v089pd43jf98dcbzfwjnnr0000gn/T/pip-req-build-3XD223/

**Comment by thomwolf** [comment]
I am uploading updated versions of the models (`en_coref_sm` is up, the others are currently being uploaded) in which I fixed the install scripts.
They should work with the original readme instructions.
You can try to download and install them (like before: `pip install MODEL_URL`).

**Comment by thomwolf** [comment]
I am gathering the feedback on the updated version of the models I just uploaded in #47.
Please mention issues with these new models there or open a new issue if needed.
