### ISSUE TITLE
A next step - recognizing more than just nouns

### ISSUE THREAD

**Issue by colingoldberg** [huggingface/neuralcoref#45]
Hi,

I tried the following sentence on the demo page "when a notification is received that a driver is available, update that fact in the database".

The demo linked "that fact" to "a driver", while I was hoping it would link "that fact" to "a driver is available".

What would it take to enable this? I hope you see this as a possibility in the not too distant future.

Colin Goldberg

**Comment by thomwolf** [comment]
Yes, thanks for sharing Colin.
I guess this is a matter of retraining a bit the model on your data. That's the next step planned so I hope we can make this kind of things work. I plan to come back refactoring the training and make it more compatible with a good annotator like [prodigy](prodi.gy) within 1-2 months. Do you have a public dataset you would like to annotate as a test with us when we'll be working on that?

**Comment by colingoldberg** [comment]
Thanks for responding. I don't have a public dataset that you could use - I have not reached that level of sophistication. But I do look forward to the growing sophistication of this tool - over time.
