### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by humehta** [huggingface/neuralcoref#46]
Code:
import spacy
import en_coref_md

nlp = en_coref_md.load()
doc = nlp(u'My sister has a dog. She loves him.')

doc._.has_coref
doc._.coref_clusters

Error:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-03395db119b1> in <module>()
      2 import en_coref_md
      3 
----> 4 nlp = en_coref_md.load()
      5 doc = nlp(u'My sister has a dog. She loves him.')
      6 

~\Anaconda3\Scripts\en_coref_md\__init__.py in load(**overrides)
     13     overrides['disable'] = disable + ['neuralcoref']
     14     nlp = load_model_from_init_py(__file__, **overrides)
---> 15     coref = neuralcoref.NeuralCoref(nlp.vocab)
     16     coref.from_disk(nlp.path / 'neuralcoref')
     17     nlp.add_pipe(coref, name='neuralcoref')

AttributeError: module 'neuralcoref' has no attribute 'NeuralCoref'

**Comment by thomwolf** [comment]
Thank I will have a look. I think this is related to Arjoonn's PR #44 .

**Comment by humehta** [comment]
Thanks!
Please do let me know!!!

**Comment by thomwolf** [comment]
Ok, I am uploading updated versions of the models (`en_coref_sm` is up, the others are currently being uploaded) in which I fixed the install scripts.
They should work with the original readme instructions.
You can try to download and install them (like before: `pip install MODEL_URL`).

**Comment by humehta** [comment]
Okay thanks!

**Comment by humehta** [comment]
ALso getting 
Failed building wheel for en-coref-sm error when running pip insall <Model Url>

**Comment by thomwolf** [comment]
Hi @humehta, which version of python are you using ? Are you under mac/linux/windows? Are you using a virtual environment (virtualenv or conda) ?

**Comment by humehta** [comment]
I am using Python 3 on windows and using conda.

**Comment by thomwolf** [comment]
I have updated the models again. Can you try to download and install again the one you use? (see my last comment in #47 )

**Comment by humehta** [comment]
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz

still gives me this error::::


 Failed building wheel for en-coref-sm
  Running setup.py clean for en-coref-sm
Failed to build en-coref-sm
anaconda-project 0.8.2 requires ruamel_yaml, which is not installed.
Installing collected packages: en-coref-sm
  Running setup.py install for en-coref-sm ... error
    Complete output from command c:\users\harsh\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\harsh\\AppData\\Local\\Temp\\pip-req-build-0vy62koe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\harsh\AppData\Local\Temp\pip-record-e1x7w7ke\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\en_coref_sm
    copying en_coref_sm\__init__.py -> build\lib.win-amd64-3.5\en_coref_sm
    creating build\lib.win-amd64-3.5\en_coref_sm\neuralcoref
    copying en_coref_sm\neuralcoref\__init__.py -> build\lib.win-amd64-3.5\en_coref_sm\neuralcoref
    copying en_coref_sm\__init__.pxd -> build\lib.win-amd64-3.5\en_coref_sm
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0
    copying en_coref_sm\en_coref_sm-3.0.0\meta.json -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0
    copying en_coref_sm\en_coref_sm-3.0.0\tokenizer -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\cfg -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\lower_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\moves -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\tok2vec_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\upper_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\ner
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\cfg -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\pairs_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\single_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors\key2row -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors\vectors -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors\key2row -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors\vectors -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\cfg -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\lower_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\moves -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\tok2vec_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\upper_model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\parser
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\tagger
    copying en_coref_sm\en_coref_sm-3.0.0\tagger\cfg -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\tagger
    copying en_coref_sm\en_coref_sm-3.0.0\tagger\model -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\tagger
    copying en_coref_sm\en_coref_sm-3.0.0\tagger\tag_map -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\tagger
    creating build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\key2row -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\lexemes.bin -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\strings.json -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\vectors -> build\lib.win-amd64-3.5\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\meta.json -> build\lib.win-amd64-3.5\en_coref_sm
    copying en_coref_sm\neuralcoref\neuralcoref.pyx -> build\lib.win-amd64-3.5\en_coref_sm\neuralcoref
    copying en_coref_sm\neuralcoref\neuralcoref.pxd -> build\lib.win-amd64-3.5\en_coref_sm\neuralcoref
    copying en_coref_sm\neuralcoref\__init__.pxd -> build\lib.win-amd64-3.5\en_coref_sm\neuralcoref
    running build_ext
    building 'en_coref_sm.neuralcoref.neuralcoref' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\harsh\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\harsh\\AppData\\Local\\Temp\\pip-req-build-0vy62koe\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\harsh\AppData\Local\Temp\pip-record-e1x7w7ke\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\harsh\AppData\Local\Temp\pip-req-build-0vy62koe\

**Comment by thomwolf** [comment]
Can you try following the windows install instructions of spaCy that are here: https://spacy.io/usage/#source-windows ? (Install a version of the Visual C++ Build Tools or Visual Studio Express that matches the version, etc ...)

**Comment by humehta** [comment]
Okay I'll try it

**Comment by humehta** [comment]
Worked thank you!!!

**Comment by sumitdas1984** [comment]
facing the same issue.
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz

  ----------------------------------------
  Failed building wheel for en-coref-sm
  Running setup.py clean for en-coref-sm
Failed to build en-coref-sm
Installing collected packages: en-coref-sm, regex
  Running setup.py install for en-coref-sm ... error
    Complete output from command C:\Users\52028512\AppData\Local\conda\conda\env
s\env_cm\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\5202
8512\\AppData\\Local\\Temp\\6\\pip-req-build-0p1wi4c4\\setup.py';f=getattr(token
ize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(
compile(code, __file__, 'exec'))" install --record C:\Users\52028512\AppData\Loc
al\Temp\6\pip-record-7x2m6ohq\install-record.txt --single-version-externally-man
aged --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\en_coref_sm
    copying en_coref_sm\__init__.py -> build\lib.win-amd64-3.6\en_coref_sm
    creating build\lib.win-amd64-3.6\en_coref_sm\neuralcoref
    copying en_coref_sm\neuralcoref\__init__.py -> build\lib.win-amd64-3.6\en_co
ref_sm\neuralcoref
    copying en_coref_sm\__init__.pxd -> build\lib.win-amd64-3.6\en_coref_sm
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0
    copying en_coref_sm\en_coref_sm-3.0.0\meta.json -> build\lib.win-amd64-3.6\e
n_coref_sm\en_coref_sm-3.0.0
    copying en_coref_sm\en_coref_sm-3.0.0\tokenizer -> build\lib.win-amd64-3.6\e
n_coref_sm\en_coref_sm-3.0.0
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\cfg -> build\lib.win-amd64-3.6\en_
coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\lower_model -> build\lib.win-amd64
-3.6\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\moves -> build\lib.win-amd64-3.6\e
n_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\tok2vec_model -> build\lib.win-amd
64-3.6\en_coref_sm\en_coref_sm-3.0.0\ner
    copying en_coref_sm\en_coref_sm-3.0.0\ner\upper_model -> build\lib.win-amd64
-3.6\en_coref_sm\en_coref_sm-3.0.0\ner
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\cfg -> build\lib.win-amd64
-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\pairs_model -> build\lib.w
in-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\single_model -> build\lib.
win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\s
tatic_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors\key2row ->
build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors

    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors\vectors ->
build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\static_vectors

    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\t
uned_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors\key2row -> b
uild\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors
    copying en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors\vectors -> b
uild\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\neuralcoref\tuned_vectors
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\cfg -> build\lib.win-amd64-3.6\
en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\lower_model -> build\lib.win-am
d64-3.6\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\moves -> build\lib.win-amd64-3.
6\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\tok2vec_model -> build\lib.win-
amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\parser
    copying en_coref_sm\en_coref_sm-3.0.0\parser\upper_model -> build\lib.win-am
d64-3.6\en_coref_sm\en_coref_sm-3.0.0\parser
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\tagger
    copying en_coref_sm\en_coref_sm-3.0.0\tagger\cfg -> build\lib.win-amd64-3.6\
en_coref_sm\en_coref_sm-3.0.0\tagger
    copying en_coref_sm\en_coref_sm-3.0.0\tagger\model -> build\lib.win-amd64-3.
6\en_coref_sm\en_coref_sm-3.0.0\tagger
    copying en_coref_sm\en_coref_sm-3.0.0\tagger\tag_map -> build\lib.win-amd64-
3.6\en_coref_sm\en_coref_sm-3.0.0\tagger
    creating build\lib.win-amd64-3.6\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\key2row -> build\lib.win-amd64-3
.6\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\lexemes.bin -> build\lib.win-amd
64-3.6\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\strings.json -> build\lib.win-am
d64-3.6\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\en_coref_sm-3.0.0\vocab\vectors -> build\lib.win-amd64-3
.6\en_coref_sm\en_coref_sm-3.0.0\vocab
    copying en_coref_sm\meta.json -> build\lib.win-amd64-3.6\en_coref_sm
    copying en_coref_sm\neuralcoref\neuralcoref.pyx -> build\lib.win-amd64-3.6\e
n_coref_sm\neuralcoref
    copying en_coref_sm\neuralcoref\neuralcoref.pxd -> build\lib.win-amd64-3.6\e
n_coref_sm\neuralcoref
    copying en_coref_sm\neuralcoref\__init__.pxd -> build\lib.win-amd64-3.6\en_c
oref_sm\neuralcoref
    running build_ext
    building 'en_coref_sm.neuralcoref.neuralcoref' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\en_coref_sm
    creating build\temp.win-amd64-3.6\Release\en_coref_sm\neuralcoref
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC
\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Use
rs\52028512\AppData\Local\conda\conda\envs\env_cm\include -IC:\Users\52028512\Ap
pData\Local\Temp\6\pip-req-build-0p1wi4c4\include -IC:\Users\52028512\AppData\Lo
cal\conda\conda\envs\env_cm\include -IC:\Users\52028512\AppData\Local\conda\cond
a\envs\env_cm\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Bui
ldTools\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Micr
osoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" /EHsc /Tp
en_coref_sm/neuralcoref/neuralcoref.cpp /Fobuild\temp.win-amd64-3.6\Release\en_c
oref_sm/neuralcoref/neuralcoref.obj
    neuralcoref.cpp
    c:\users\52028512\appdata\local\conda\conda\envs\env_cm\include\pyconfig.h(5
9): fatal error C1083: Cannot open include file: 'io.h': No such file or directo
ry
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Buil
dTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exi
t status 2

**Comment by sumitdas1984** [comment]
Installed Visual C++ build tool that matches the version as pointed out by previous replies. But still getting the same error.
System configuration where I'm trying this out
Windows Server 2012 R2
64 bit
Python 3.6.8

Please help me resolving this issue.
