### ISSUE TITLE
Unable to run Demo to due to Unicode Decode Error

### ISSUE THREAD

**Issue by christfan868** [huggingface/neuralcoref#5]
When tryning to run the demo source code, this is the error I get:
**UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5547: character maps to < undefined >**

I am currently running Python 3. 5, spaCy 1.9.0 and I have all the dependencies installed.

**Comment by rlpatsh** [comment]
Resolved it by changing data.py line 238 to 

`        with open(name+"_vocabulary.txt", encoding="utf8") as f:
`

**Comment by richcamp** [comment]
Appears to be a typo in previous:  should be line 338 that's changed.

**Comment by nodyyu89** [comment]
Hi there, When tryning to run the demo source code, this is the error I get:

## embeddings_from_file(model_path + "static_word")
  File "C:\Users\<my python dictionary>\site-packages\neuralcoref\data.py", line 339, in load_embeddings_from_file
    for i, line in enumerate(f):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 2463: illegal multibyte sequence

I am currently running Python 3.4 , spaCy 2. 0, using the model 'en_core_web_sm' and I have all the dependencies installed.

I tried to add this to data.py line 338: 
## with open(name+"_vocabulary.txt", encoding="utf8") as f:
or 
## with open(name+"_vocabulary.txt", encoding="gdk") as f:

All these don't work.
any ideas? Thx

**Comment by eyb1** [comment]
For search engines, error is:

    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 626: character maps to <undefined>

Thanks for the above solution guys.

**Comment by theSage21** [comment]
I've come across files which hasve 'latin1' encodings. You can try out 'latin1' as the encoding if 'utf-8' does not fix it.

**Comment by khliu1238** [comment]
demo source code gone now? I didn't see any.

**Comment by thomwolf** [comment]
We are now on release v3.0 so I am closing this old issue.
Feel free to open it again (or a new one) if you are experiencing some issues with the new release.
