### ISSUE TITLE
AssertionError when loading model in Ubuntu

### ISSUE THREAD

**Issue by d99kris** [huggingface/neuralcoref#56]
Hi,
Firstly, thanks for the work on neuralcoref, it seems like a very useful extension to spaCy.

I successfully installed the neuralcoref model using:
```sudo pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz```

But when I try to use it / load the model, like this:
```
#!/usr/bin/env python

import spacy
nlp = spacy.load("en_coref_sm")
doc = nlp(u'My sister has a dog. She loves him.')
```

I'm getting the following error:
```
Traceback (most recent call last):
  File "./f.py", line 4, in <module>
    nlp = spacy.load("en_coref_sm")
  File "/home/d99kris/.local/lib/python2.7/site-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/home/d99kris/.local/lib/python2.7/site-packages/spacy/util.py", line 114, in load_model
    return load_model_from_package(name, **overrides)
  File "/home/d99kris/.local/lib/python2.7/site-packages/spacy/util.py", line 137, in load_model_from_package
    return cls.load(**overrides)
  File "/usr/local/lib/python2.7/dist-packages/en_coref_sm/__init__.py", line 15, in load
    coref = NeuralCoref(nlp.vocab)
  File "neuralcoref.pyx", line 527, in en_coref_sm.neuralcoref.neuralcoref.NeuralCoref.__init__
  File "doc.pyx", line 99, in spacy.tokens.doc.Doc.set_extension
AssertionError
```
(Also getting the same error if downloading and trying to load en_coref_md)

Any ideas what could be wrong?

**Comment by thomwolf** [comment]
That's a bit strange. What is also strange it that spaCy's errors messages are more explicits in the latest version. Can you try updating spaCy maybe?

The best would be to create a clean virtual environment using conda or virtual env, and install the model in this environment. That would give you the latest spaCy and a clean version of neuralcoref at the same time.

**Comment by d99kris** [comment]
Thanks a lot! I should've tried that before reporting the issue. I set up a clean virtualenv and then installed the stuff using:
```
pip install spacy
python -m spacy download en_core_web_sm
pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_sm-3.0.0/en_coref_sm-3.0.0.tar.gz
```
After that everything works fine! I'm not sure what fixed it, but probably getting the latest spaCy did the trick. Thanks again for the help.

**Comment by qacollective** [comment]
Upgrading Spacy from 2.0.3 to 2.0.11 worked for me too, without any need for virtualenv or conda.
