### ISSUE TITLE
Using OntoNotes 5.0 to generate coNLL files

### ISSUE THREAD

**Issue by vrian** [huggingface/neuralcoref#60]
**Description**
I am currently stucked at the "Get the data" section for training the neural coreference model. As a newbie, I have little understanding of converting the skeleton files to conll files. Here are the commands specified in the guide: 

`skeleton2conll.sh  -D [path_to_ontonotes_train_folder] [path_to_skeleton_train_folder]
skeleton2conll.sh  -D [path_to_ontonotes_test_folder] [path_to_skeleton_test_folder]
skeleton2conll.sh  -D [path_to_ontonotes_dev_folder] [path_to_skeleton_dev_folder]`  
h

**Result**

Here is my command. 
![image](https://user-images.githubusercontent.com/7411123/41773710-98a6c186-764f-11e8-8b50-f4a332792ddd.png)

Here is the output in case image wont load:

 `$ ".\conll-2012-scripts\conll-2012\v3\scripts\skeleton2conll.sh" -D ".\ontonotes-release-5.0\data\files\data\" ".\conll-2012-train\conll-2012\"`
`
please make sure that you are pointing to the directory 'conll-2012'
`

**Data**
OntoNotes 5.0 from LDC (thru email)
Training, and Development data (both are v4)
Test Data (Official, v9)
CoNLL 2012 scripts (v3)
last four from [this link](http://conll.cemantix.org/2012/data.html)

**Steps to reproduce**
1. Download the data
2. Extract the data
3. Run the command `skeleton2conll.sh -D [path/to/conll-2012-train-v0/data/files/data] [path/to/conll-2012]`

**Build/Platform**
Windows 10
Git Bash (mingw64)
python 3.6
cpu (no CUDA)

Alternatively, if someone knows how to use [conll-formatted Onotnotes 5.0](https://github.com/ontonotes/conll-formatted-ontonotes-5.0/tree/master/conll-formatted-ontonotes-5.0), I can also put an issue about it.

**Comment by thomwolf** [comment]
Hi @vrian,
Can you try to follow the instructions and scripts from this page: http://cemantix.org/data/ontonotes.html
I think they are more up to date than the shared task ones (I will update the readme).
There is an example on how to use `skeleton2conll.sh`.

**Comment by vrian** [comment]
Thanks @thomwolf! I see that's the conll-formatted one. I also tried it but the error is the same. Here is the issue I made about it

**Comment by thomwolf** [comment]
You have to follow carefully the example given on http://cemantix.org/data/ontonotes.html regarding how to use the scripts. Replace the path given in the example by the path to the CoNLL data folder on your computer.

If you have an error again, please post the new error here.
I don't think it can be the exact same error as in your first message as the script was updated on that error.

**Comment by vrian** [comment]
I rechecked the instructions carefully and made some progress. A different error is displayed

`-> python conll-formatted-ontonotes-5.0/scripts/skeleton2conll.py ontonotes-release-5.0/data/files/data/english/annotations/bc/cnn/00/cnn_0001.parse conll-formatted-ontonotes-5.0/data/train/data/english/annotations/bc/cnn/00/cnn_0001.gold_skel conll-formatted-ontonotes-5.0/data/train/data/english/annotations/bc/cnn/00/cnn_0001.gold_conll -edited --text
  File "conll-formatted-ontonotes-5.0/scripts/skeleton2conll.py", line 392
    except InvalidSexprException, e:
                                ^
SyntaxError: invalid syntax
Exit code: 1
conll-formatted-ontonotes-5.0/scripts/skeleton2conll.sh: line 93: break: only meaningful in a 'for', 'while', or 'until' loop
`

the command I ran is:

`$ "conll-formatted-ontonotes-5.0/scripts/skeleton2conll.sh" -D "ontonotes-release-5.0/data/files/data" "conll-formatted-ontonotes-5.0/"
`

I am using Python 3.6.5 64-bit

here are the tree directory in case:

![image](https://user-images.githubusercontent.com/7411123/42094429-575eecc4-7be2-11e8-8799-e72492a3518e.png)

![image](https://user-images.githubusercontent.com/7411123/42094644-049b32bc-7be3-11e8-89da-3fed4d102873.png)

**Comment by fancyerii** [comment]
it seems some conll scripts can only use python 2.x

**Comment by rgabbard** [comment]
Should anyone else run into the `please make sure that you are pointing to the directory 'conll-2012'` problem in the future, it looks like the script expects the command-line argument to be exactly the string "conll-2012" and not some alternate relative or absolute path which points to the same directory.  As a consequence, you need to run the script from the parent directory of `conll-2012` so you can use that string exactly as the argument

**Comment by d5555** [comment]
Hi, @vrian , did you solve the problem ?

**Comment by marc88** [comment]
@rgabbard Did your suggestion solve your problem? Not working for me though.

**Comment by rgabbard** [comment]
@marc88 : yes, my solution worked in my case

**Comment by marc88** [comment]
@rgabbard Just in case if you may suggest, I found a github repo for the files here
https://github.com/ontonotes/conll-formatted-ontonotes-5.0

Can you validate if the scripts produce a similar file as they are in the repo above?  So, if I can just use the files in the repo above without waiting for the script to work?

Regards

**Comment by swaroopgrs** [comment]
@vrian you can convert the `skeleton2conll.sh` file into python 3 with something like 

`2to3 -w skeleton2conll.sh`

**Comment by hoangcuong2011** [comment]
Using Python 2 is perhaps the simplest way to solve the issue!
