### ISSUE TITLE
Can't detect 'former' and 'latter' as potential references.

### ISSUE THREAD

**Issue by blackeagle01** [huggingface/neuralcoref#61]
In sentences like:

I like chicken and cheese. Although, I like the former better.

The word former is referencing to chicken but the system is unable to detect any coreference.

**Comment by thomwolf** [comment]
That's an interesting problem, thanks.
So here one issue is that `the former` is not even detected as a potential mention as it is an adjective used as a noun and not a noun or pronoun in it-self. Linguistically it's a bit complex to handle.
I will give it a look next time I am working on the model it-self.
