### ISSUE TITLE
Help: Can't reproduce demo

### ISSUE THREAD

**Issue by kubicki14** [huggingface/neuralcoref#63]
Hey Thomas! First and foremost I wanted to say that you are amazing and this is great work! 

My question pertains to how your demo website model is running, in comparison to my local copy.
(https://huggingface.co/coref/)

I have a line of text that has nouns and pronouns in the second sentence, and your demo is correctly making an association! However when I use the en_coref_md pre-trained spacy model locally on the same text I get:
'doc._.has_coref' = FALSE.

And when I look at the other parts of the Doc, Span, and Token objects I get NoneType objects as well.

I'm not sure why I'm not seeing associations similar to your demo, nor do I know how to reproduce 
 what's being outputted on your site.

I don't have the time to annotate and train on my current data, so this is me hoping your pre-trained english model will work well on my data. (Which it seems to?)

To re-iterate: What are you using as a model for the site? And any reason why I can't see nominal and pronominal associations when they are available in the demo?

Any and all help is appreciated! Thank you again.

**Comment by thomwolf** [comment]
Hmm the site is running an older version of NeuralCoref (v1 in fact) with spaCy 1 so there are indeed so differences.
Two things:
- have you tried with `en_coref_lg`?
- can you give me an example of sentence and coref that work on the demo and not with your version?

**Comment by kubicki14** [comment]
I have yet to try the larger model because of size difference and I'm assuming the runtime overhead wouldn't be worth it, but I will try it if you think I will get different results. My application is clinical so I'll post this example:

"Left adnexal cystic lesion measures 4.3 x 3.8 cm.  It appears increased from the prior examination measurement of 2.0 x 2.0 cm.  This is indeterminate but may represent a hemorrhagic cyst possibly endometrioma but this requires clinical correlation"

Again this might be a lost cause because I'm trying to use this on different text than the model would expect, but when run in Debug mode on the demo site if gives decent weight associations between lesion, this, and it.

**Comment by thomwolf** [comment]
Hi @kubicki14, yes the text looks very different from the training data so it's really hard to predict what the statistical model will guess. We will be releasing a version that let you more simply retrain the model on your data but that won't before a few months.
In the mean time I would recommend using the largest model `en_coref_lg`.

**Comment by devitoclic** [comment]
Same problem here. Online demo resolve corefs with custom words and expressions but using the latest neuralcoref package in local environment returns `doc._.has_coref = False` for the same example. How many examples do we need to adapt the model to custom data?

**Comment by thumarrushik** [comment]
Same problem here
