### ISSUE TITLE
Cannot access conllparser.py

### ISSUE THREAD

**Issue by basilgeorge** [huggingface/neuralcoref#68]
Hi
I am not able to access the conllparser.py script here: https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/conllparser.py

I find no folder named blob in the repository.

Could you please check?

Thanks,
Basil.

**Comment by thomwolf** [comment]
Oh yes, it's all there now: https://github.com/huggingface/neuralcoref/tree/master/neuralcoref/train
I am refactoring the training scripts to make it faster but it won't be finished before a few weeks I think.

**Comment by basilgeorge** [comment]
Thanks! @thomwolf
