### ISSUE TITLE
No clusters being formed. But rest api shows it

### ISSUE THREAD

**Issue by NeverInAsh** [huggingface/neuralcoref#69]
import en_coref_lg
nlp = en_coref_lg.load()
sentence = u'Thirty-nine patients received single-dose BI 655066 intravenously with arm size of 18 or subcutaneously with arm size of 13 or placebo with arm size of 8.'
doc = nlp(sentence)
doc._.coref_clusters

There seems to be no coref clusters but https://huggingface.co/coref/?text=Thirty-nine%20patients%20received%20single-dose%20BI%20655066%20intravenously%20with%20arm%20size%20of%2018%20or%20subcutaneously%20with%20arm%20size%20of%2013%20or%20placebo%20with%20arm%20size%20of%208. tells a different story.

**Comment by NeverInAsh** [comment]
Also 
doc = nlp(u'Hello anshik is an engineer,he lives in India')
doc._.coref_clusters #output [anshik: [anshik, he]]

doc = nlp(u'Hello anshik is an engineer,he lives in Lucknow') #lucknow is capital of Uttar Pradesh(state of India)
doc._.coref_clusters #output [an engineer: [an engineer, he]]

**Comment by theSage21** [comment]
See #30 #16 as they might solve your issue. As for the other example, using non-western names often causes strange parses. For example using `Hello John is an engineer,he lives in Lucknow` solves that last part.

**Comment by NeverInAsh** [comment]
@theSage21 thanks for such a quick response. I understand what you are trying to say. #30 is what i am looking for but doesn't solve for my problem.

Maybe i am missing something.see this link 
https://huggingface.co/coref/?text=Obama%20was%20born%20in%201961%20in%20Honolulu%2C%20Hawaii%2C%20two%20years%20after%20the%20territory%20was%20admitted%20to%20the%20Union%20as%20the%2050th%20state.

This is a pretty normal text, but the server again does some magic and python package is failing.Is there a way i can download the information on server in XML.

The medium post is just excellent and got me really excited, but how is working so perfectly @ https://huggingface.co/coref/?text= and not in python packages @thomwolf.

**Comment by thomwolf** [comment]
@NeverInAsh the coref demo on our website also shows no coreference clusters for your sentence `Thirty-nine patients received single-dose BI 655066 intravenously with arm size of 18 or subcutaneously with arm size of 13 or placebo with arm size of 8`

You have to unclick the `debug` box on the website to see the real output of the coreference module. The other branches show all the scores computed but the model only keeps the best scores to compute the clusters.

One reason there is no cluster while we can see interesting pair-wise scores is that there is a `greedyness` coefficient that controls the balance between favoring single-mentions and favoring pair-mentions.

This `greedyness` coefficient is currently hardcoded in NeuralCoref. I will try to make it adjustable so people with out-of-domain dataset (like your medical dataset) can lower it to get more coreference clusters.

**Comment by NeverInAsh** [comment]
This makes complete sense to me. Thanks @thomwolf , i think an adjustable greedyness coefficient would be a great addition to you and your team's awesome effort.

**Comment by boehm-e** [comment]
@NeverInAsh 
you can tweak greedyness coefficient : 
https://github.com/huggingface/neuralcoref/blob/develop/readme.rst

```nc = NeuralCoref(nlp.vocab).from_disk('path/to/neuralcoref/weights')```
**```nc.cfg['greedyness'] = 0.75```**
```nlp.add_pipe(nc)```

**Comment by thumarrushik** [comment]
@boehm-e 

I am getting below mentioned where I follow your instructions.


```
AttributeError: [E047] Can't assign a value to unregistered extension attribute 'coref_scores'. Did you forget to call the `set_extension` method?
```

**Comment by boehm-e** [comment]
@thumarrushik can you share a code snippet ?

**Comment by thumarrushik** [comment]
@boehm-e 

It's work on Ubuntu, still not getting whatever results get in the rest API, is there any tuning method available, please suggest me.


import spacy
from neuralcoref import NeuralCoref


nlp = spacy.load('en')

nc = NeuralCoref(nlp.vocab).from_disk('/home/ubuntu/neuralcoref')
nc.cfg['greedyness'] = 0.56
nlp.add_pipe(nc)
doc = nlp(u'text ')
doc._.coref_clusters

**Comment by boehm-e** [comment]
@thumarrushik : if you're not getting the same results it probably means that they 'website' is not using the same model as they released.
Increasing the greedyness will allow you to find more clusters, but with lower confidence...

**Comment by thumarrushik** [comment]
@boehm-e  Thank you for your help and I am following your new issue in this repository

**Comment by thomwolf** [comment]
There is now an adjustable `greedyness` coefficient (see readme for the new release 4.0)
