### ISSUE TITLE
How to get the confidence score of the coreference?

### ISSUE THREAD

**Issue by meggie-wong** [huggingface/neuralcoref#70]
![1530588879488](https://user-images.githubusercontent.com/35553398/42197397-214515fc-7eb5-11e8-9b69-37a2f297dad0.jpg)

I have noticed that in your deme there are some scores for the coreference but how can i get the score from the api? 

Does someone know?

Thanks!

**Comment by thomwolf** [comment]
Hi, currently you cannot with the version 3.0 of NeuralCoref.
I will see if I can add a way to access them again.

**Comment by aribornstein** [comment]
Any progress on this?

**Comment by MinHyung-Kang** [comment]
Bumping this issue! Would be very helpful to be able to access them.

**Comment by thomwolf** [comment]
Added in the new version (see the readme for the new release 4.0).
