### ISSUE TITLE
Reference paper of this system

### ISSUE THREAD

**Issue by SeanCherngTW** [huggingface/neuralcoref#71]
Hi,

What thesis did you refer to implement the neuralcoref model?

Thanks

**Comment by thomwolf** [comment]
Hi, it based on the model developed in these two papers by Kevin Clark and Christopher D. Manning: https://cs.stanford.edu/~kevclark/
- Deep Reinforcement Learning for Mention-Ranking Coreference Models. 
by Kevin Clark and Christopher D. Manning in Empirical Methods on Natural Language Processing (EMNLP), 2016. 
- Improving Coreference Resolution by Learning Entity-Level Distributed Representations. 
by Kevin Clark and Christopher D. Manning in Association for Computational Linguistics (ACL), 2016.
