### ISSUE TITLE
Can't find model 'en_coref_sm'.

### ISSUE THREAD

**Issue by qhungngo** [huggingface/neuralcoref#76]
According to guide to install neuralcoref by source code, I have done successfully but when I run example, spacy package could not find 'en_coref_sm' model.

> OSError: [E050] Can't find model 'en_coref_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Anyone know how to fix this?
Thanks.

**Comment by theSage21** [comment]
I don't think the models would be included in the source code. You'll either have to train or download from the link in the README.

Any reason you want a source install?

**Comment by folterj** [comment]
How can we get neuralcoref (models) to work with spaCy 2.0.0.18 (published dec 2018) - making the original question very valid.

Indeed the page describes neurocoref can be downloaded from source (assuming this serves a point):
https://github.com/huggingface/neuralcoref#install-neuralcoref-from-source
So can we get the coref models to work with this?

**Comment by thomwolf** [comment]
This should be fixed in the new release (4.0) with SpaCy 2.1+ (which is also on PyPI now).
We should be compatible with any SpaCy model now.
Please open a new issue if you still experience issues.
