### ISSUE TITLE
Performance issue for the latest version.

### ISSUE THREAD

**Issue by sanjanarjn** [huggingface/neuralcoref#77]
Hi,

I have installed the latest version of neural coref and Cython also. But for a 22k long content it is taking around 1 min to resolve the coreference. Is this expected? How do I make sue if Cython is being used for better performance? Kindly help. Thanks in advance.

Sanjana

**Comment by arunzz** [comment]
I am also facing the same issue. Its isnt fast enough. Kindly let know if anything else has to be installed to realize the speed in this latest version.

**Comment by theSage21** [comment]
I'll run some tests to verify this. I've found the speed satisfactory so far.

**Comment by theSage21** [comment]
model|words|real|user|sys
-----|-----|----|----|---                                                                                                               
en_coref_lg|59014|49.9533|91.5734|14.6637
en_coref_md|59014|58.9120|101.1673|14.5475
en_coref_sm|59014|42.6424|86.9106|13.8428

Times are in seconds as obtained by the linux `time` command. The text used was
[text.txt](https://github.com/huggingface/neuralcoref/files/2213438/text.txt).

That's approximately 1100 words per second on a 4 core laptop.

**Comment by arunzz** [comment]
Thank you for sharing this detail.
It is fast enough when all cores are utilized.

Regards
Arun

**Comment by Rushin95** [comment]
Hi Everyone, 

I tried running **NeurelCoref en_coref_sm model** to get co-reference resolution from a text. Following are the details:

_Input Doc type: Text file
Input Doc size : 834 KB
Total sentences : 7199 
Total words: 126488
Processing Time: 10 minutes_

**Problem:**
This program is eating up all my RAM. All 8 cores(32 GB machine) are used with **7 GB to 29 GB** Memory utilization. Mostly, memory usage remains above 20 GB. Also the **processing time is too high** for me. 

Is there a way to bring this **execution time to seconds** ? Also, how handle the **memory usage issue**?

Hope to get some help. Thanks.
