### ISSUE TITLE
Two resolutions in one

### ISSUE THREAD

**Issue by arunzz** [huggingface/neuralcoref#80]
Hi

In the below sentence, the pronominals "_their_" is resolved with "_designers_" and "_them_" is resolved with "_designers_". But actually "_them_" has to be resolved with "_implanted devices_" if you see the sentence meaning.
Any way to learn this or is this even feasible. Kindly let know if this is something that we have to live with.

**Sentence**
This quality allows **designers** to reduce the size and scale of **their** implanted devices to make **them** less intrusive.

**Comment by thomwolf** [comment]
Hi, I don't think it can be changed in the current version unfortunately.
I am working on an annotation system that could help for that but it will still take a few month to be ready.
