### ISSUE TITLE
Do you have any well-trained Chinese spaCy  models？

### ISSUE THREAD

**Issue by tanzf** [huggingface/neuralcoref#84]
Do you have any well-trained Chinese spaCy  models？can you send me a copy? Email：tanzfzb@163.com

**Comment by thomwolf** [comment]
Hi,
No I don't have a chinese model.
Best,
Thom

**Comment by lowpair** [comment]
@tanzf 
https://github.com/howl-anderson/Chinese_models_for_SpaCy 
you can train it yourself!
