### ISSUE TITLE
How to combine multiple clusters for the same entity?

### ISSUE THREAD

**Issue by FTAsr** [huggingface/neuralcoref#86]
In longer documents, the algorithm generates several clusters each including a few (neighbouring) mentions of a named entity. Is there a standard way to combine them so the resulting number of clusters would be equal to the number of unique entities?

**Comment by thomwolf** [comment]
Hi, I don't think there is a universal way to combine clusters.
The algorithm try to cluster entities as much as it can.
If it's not enough you will have to add domain specific heuristics.
