### ISSUE TITLE
prepare the data error

### ISSUE THREAD

**Issue by w2wei** [huggingface/neuralcoref#89]
"python -m neuralcoref.conllparser --path ./data/train/"  returns an error message "AttributeError: 'ConllDoc' object has no attribute '_extract_mentions'"

The traceback is as below, 
🌋 Parsing utterances and filling docs
0it [00:00, ?it/s]
Traceback (most recent call last):
  File ".../python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".../python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../neuralcoref/neuralcoref/conllparser.py", line 711, in <module>
    CORPUS.read_corpus(args.path)
  File ".../neuralcoref/neuralcoref/conllparser.py", line 618, in read_corpus
    use_gold_mentions=self.use_gold_mentions)
  File ".../neuralcoref/neuralcoref/conllparser.py", line 318, in add_conll_utterance
    self._extract_mentions(parsed, len(self.utterances), self.n_sents, self.speakers[speaker_id])

Method _extract_mentions is missing from class ConllDoc or class Document

**Comment by andreasvc** [comment]
@thomwolf Any word on this? It seems to me that the method is missing from the code base.

**Comment by w2wei** [comment]
Hi @LexieGrace ! No, this method is not in class ConllDoc or class Document. There are two relevant functions extract_mentions_spans and _extract_from_sent in document.py. I guess the code is refactorized and this method is no longer used.

**Comment by LexieGrace** [comment]
Thanks for responding! I saw them. Currently using them for my mention extraction.

**Comment by thomwolf** [comment]
Yes, the training code is currently being refactored to speed it up.
Work on progress on the `develop` branch

**Comment by emilykl** [comment]
@thomwolf to get the training working right now, is there a single function I can use instead of `_extract_mentions()`?

**Comment by msalameh83** [comment]
any solution to the issue above?
I am facing the same issue

**Comment by d5555** [comment]
@thomwolf , Could you help with a quick fix to this problem please? 
I got same error , Method _extract_mentions is missing from class ConllDoc or class Document

**Comment by thomwolf** [comment]
Yes, the training scripts are outdated. They are next on my to-do but I don't have an ETA yet.
