### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by kleinias** [huggingface/neuralcoref#9]
`s@hello:~/code/neuralcoref$ python -m spacy download 'en'

    Downloading en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-1.2.0/en_core_web_sm-1.2.0.tar.gz (52.2MB)
    100% |████████████████████████████████| 52.2MB 2.1MB/s 
Collecting spacy<2.0.0,>=1.7.0 (from en-core-web-sm==1.2.0)
  Downloading spacy-1.10.0.tar.gz (3.4MB)
    100% |████████████████████████████████| 3.4MB 3.8MB/s 
Collecting numpy>=1.7 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading numpy-1.13.3-cp27-cp27mu-manylinux1_x86_64.whl (16.6MB)
    100% |████████████████████████████████| 16.7MB 2.6MB/s 
Collecting murmurhash<0.27,>=0.26 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading murmurhash-0.26.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cymem<1.32,>=1.30 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading cymem-1.31.2-cp27-cp27mu-manylinux1_x86_64.whl (66kB)
    100% |████████████████████████████████| 71kB 5.4MB/s 
Collecting preshed<2.0.0,>=1.0.0 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading preshed-1.0.0.tar.gz (89kB)
    100% |████████████████████████████████| 92kB 3.8MB/s 
Collecting thinc<6.6.0,>=6.5.0 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading thinc-6.5.2.tar.gz (926kB)
    100% |████████████████████████████████| 931kB 2.6MB/s 
Collecting plac<1.0.0,>=0.9.6 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading plac-0.9.6-py2.py3-none-any.whl
Collecting pip<10.0.0,>=9.0.0 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 2.7MB/s 
Collecting six (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting pathlib (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 6.4MB/s 
Collecting ujson>=1.35 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 2.8MB/s 
Collecting dill<0.3,>=0.2 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading dill-0.2.7.1.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 4.5MB/s 
Collecting requests<3.0.0,>=2.13.0 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 2.9MB/s 
Collecting regex<2017.12.1,>=2017.4.1 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading regex-2017.11.09.tar.gz (608kB)
    100% |████████████████████████████████| 614kB 3.2MB/s 
Collecting ftfy<5.0.0,>=4.4.2 (from spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading ftfy-4.4.3.tar.gz (50kB)
    100% |████████████████████████████████| 51kB 6.6MB/s 
Collecting wrapt (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading wrapt-1.10.11.tar.gz
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading tqdm-4.19.4-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 8.0MB/s 
Collecting cytoolz<0.9,>=0.8 (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading cytoolz-0.8.2.tar.gz (386kB)
    100% |████████████████████████████████| 389kB 2.7MB/s 
Collecting termcolor (from thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading termcolor-1.1.0.tar.gz
Collecting idna<2.7,>=2.5 (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.1MB/s 
Collecting urllib3<1.23,>=1.21.1 (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 3.5MB/s 
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    100% |████████████████████████████████| 337kB 3.4MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.13.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 3.5MB/s 
Collecting html5lib (from ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading html5lib-0.999999999-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 122kB 3.7MB/s 
Collecting wcwidth (from ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Collecting toolz>=0.8.0 (from cytoolz<0.9,>=0.8->thinc<6.6.0,>=6.5.0->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading toolz-0.8.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 7.1MB/s 
Collecting webencodings (from html5lib->ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Collecting setuptools>=18.5 (from html5lib->ftfy<5.0.0,>=4.4.2->spacy<2.0.0,>=1.7.0->en-core-web-sm==1.2.0)
  Downloading setuptools-36.7.2-py2.py3-none-any.whl (482kB)
    100% |████████████████████████████████| 491kB 3.0MB/s 
Installing collected packages: numpy, murmurhash, cymem, preshed, wrapt, tqdm, toolz, cytoolz, plac, six, dill, termcolor, pathlib, thinc, pip, ujson, idna, urllib3, certifi, chardet, requests, regex, webencodings, setuptools, html5lib, wcwidth, ftfy, spacy, en-core-web-sm
  Running setup.py install for preshed ... done
  Running setup.py install for wrapt ... done
  Running setup.py install for toolz ... done
  Running setup.py install for cytoolz ... done
  Running setup.py install for dill ... done
  Running setup.py install for termcolor ... done
  Running setup.py install for pathlib ... done
  Running setup.py install for thinc ... done
  Running setup.py install for ujson ... done
  Running setup.py install for regex ... done
  Running setup.py install for ftfy ... done
  Running setup.py install for spacy ... done
  Running setup.py install for en-core-web-sm ... done
Successfully installed certifi-2017.11.5 chardet-3.0.4 cymem-1.31.2 cytoolz-0.8.2 dill-0.2.7.1 en-core-web-sm-2.0.0 ftfy-4.4.3 html5lib-0.999999999 idna-2.6 murmurhash-0.28.0 numpy-1.13.3 pathlib-1.0.1 pip-9.0.1 plac-0.9.6 preshed-1.0.0 regex-2017.11.9 requests-2.18.4 setuptools-36.7.2 six-1.11.0 spacy-2.0.2 termcolor-1.1.0 thinc-6.10.0 toolz-0.8.2 tqdm-4.19.4 ujson-1.35 urllib3-1.22 wcwidth-0.1.7 webencodings-0.5.1 wrapt-1.10.11
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/s/.local/lib/python2.7/site-packages/spacy/__main__.py", line 133, in <module>
    plac.Interpreter.call(CLI)
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 1142, in call
    print(out)
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 914, in __exit__
    self.close(exctype, exc, tb)
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 952, in close
    self._interpreter.throw(exctype, exc, tb)
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 964, in _make_interpreter
    arglist = yield task
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 1139, in call
    raise_(task.etype, task.exc, task.tb)
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 380, in _wrap
    for value in genobj:
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 95, in gen_exc
    raise_(etype, exc, tb)
  File "/home/s/.local/lib/python2.7/site-packages/plac_ext.py", line 966, in _make_interpreter
    cmd, result = self.parser.consume(arglist)
  File "/home/s/.local/lib/python2.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/s/.local/lib/python2.7/site-packages/spacy/__main__.py", line 33, in download
    cli_download(model, direct)
  File "/home/s/.local/lib/python2.7/site-packages/spacy/cli/download.py", line 24, in download
    link_package(model_name, model, force=True)
  File "/home/s/.local/lib/python2.7/site-packages/spacy/cli/link.py", line 22, in link_package
    pkg = importlib.import_module(package_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/s/.local/lib/python2.7/site-packages/en_core_web_sm/__init__.py", line 5, in <module>
    from spacy.util import load_model_from_init_py, get_model_meta
ImportError: cannot import name load_model_from_init_py
Segmentation fault
`

**Comment by julien-c** [comment]
I see a `spacy-2.0.2` in there, but we need `spacy-1.x`

**Comment by julien-c** [comment]
Closing this as it's not related to this project

**Comment by rbhambriiit** [comment]
This does not support spacy2 today?

**Comment by julien-c** [comment]
Yes it does, this was an old issue
