### ISSUE TITLE
Cannot import Coref

### ISSUE THREAD

**Issue by iovian** [huggingface/neuralcoref#91]
I want to use one_shot_coref(text) function from Coref but when I try to import it an error is raised:

import en_core_web_md
spacy = en_core_web_md.load()
coref = Coref(nlp=spacy)

ImportError: cannot import name 'Coref'

**Comment by thomwolf** [comment]
Hi,
Try to follow the instructions in the readme, it should work:
```
import en_coref_md

nlp = en_coref_md.load()
doc = nlp(u'My sister has a dog. She loves him.')

doc._.has_coref
doc._.coref_clusters
```

**Comment by MattJBritton** [comment]
Sorry to re-open this, but I am having the same confusion. I initially tried to use the same code as the OP to load, having found that on a blog post that used one_shot_coref. The [spacy documentation](https://spacy.io/universe/?id=neuralcoref.
) for neuralcoref also uses this load method.

I have also tried the loading method from the readme - it loads as expected, but I am unsure how to access one_shot_coref from the doc object.

Alternately, can you recommend a fast way to simply replace every pronoun with the most likely "resolved utterance"? Apologies if I missed this, but I'm unclear on how to do this based on the readme.

Thanks!

**Comment by MattJBritton** [comment]
Or, sorry, is the best way to do this just doc._.coref_resolved? Apologies if that's the case and I missed it earlier.

**Comment by thomwolf** [comment]
Oh yes doc._.coref_resolved should be the same as previous one_shot_coref. we changed that to fit better with spaCy.
