### ISSUE TITLE
Installation Problem of en_coref_md

### ISSUE THREAD

**Issue by hpwow** [huggingface/neuralcoref#93]
When I used pip install en_coref_md, I got 'could not find a version that satisfies the requirement en_coref_md (from versions: ) No matching distribution found for en_coref_md'. But I checked all my python and spacy versions. Can anyone help?

**Comment by theSage21** [comment]
The link is meant to be used.

Instead of using `pip install en_coref_md` use `pip install https://github.com/huggingface/neuralcoref-models/releases/download/en_coref_md-3.0.0/en_coref_md-3.0.0.tar.gz`

**Comment by thomwolf** [comment]
Thanks Arjoonn!
