### ISSUE TITLE
how to download OntoNotes data in that website?

### ISSUE THREAD

**Issue by hezhihao10** [huggingface/neuralcoref#94]
I have log in my account, but  I still can not find the button to download the dataset in the website(https://catalog.ldc.upenn.edu/LDC2013T19).Someone told me that I should create a order. Could you tell me where should I click to create the order? Thank you a lot.

**Comment by julien-c** [comment]
Hi, your best bet would be to ask the LDC directly, they're usually pretty responsive.

**Comment by KavyaGujjala** [comment]
> I have log in my account, but I still can not find the button to download the dataset in the website(https://catalog.ldc.upenn.edu/LDC2013T19).Someone told me that I should create a order. Could you tell me where should I click to create the order? Thank you a lot.

Hi, Did you download the dataset? If so, how did you do it? Even I am trying to download.

**Comment by jackfromeast** [comment]
Hi, I just downloaded the dataset and it takes me a few days. Only organization members can access the dataset, so after you register on the LDC, it's important to ask the LDC office to give you the contact information of your organization's administrator, who is able to verify and accept your membership application. After you get the membership, you are able to download the dataset :>
