### ISSUE TITLE
Are the scores returned ReLU?

### ISSUE THREAD

**Issue by SanjanaLokesh** [huggingface/neuralcoref#95]
I went through the code which calculates the score and it looks like its supposed to be ReLU scores. But I don't understand or see why we get negative scores in ReLU since the point of using ReLU is to get the positive scores. Unless my understanding on how the scores are calculated is wrong.

**Comment by thomwolf** [comment]
Hi, the model has three layers with ReLU followed by two linear layers so negative scores can indeed arise from the two last layers. Here is the model (using spaCy's Thinc librairy notation):
```
ReLu(h1, SIZE_PAIR_IN) >> ReLu(h2, h1) >> ReLu(h3, h2) >> Affine(1, h3) >> Affine(1, 1)
```
https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/neuralcoref.pyx#L491

**Comment by SanjanaLokesh** [comment]
Hi @thomwolf Thank you for clarifying that. Is there a way to convert these scores to be between 0 and 100. It is more readable to get a confidence or sorts as a value.
