### ISSUE TITLE
Score normalization

### ISSUE THREAD

**Issue by sanjanalreddy** [huggingface/neuralcoref#99]
How do you normalize the scores which are returned? And how do you interpret the scores which are returned?

**Comment by thomwolf** [comment]
Well, you can't really normalize the scores. They are not probabilities (not trained using a probabilistic loss). You can just compare them to one another: higher or lower than another score.

**Comment by aribornstein** [comment]
@thomwolf is there any best practice for thresholding?

**Comment by thomwolf** [comment]
Hi, none that I'm aware of unfortunately. In the new release (0.4), you can use the `greedyness`parameter to adjust the comparison between singleton and pairwise scores.
